// frontend/src/components/MonacoQueryEditor.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, shallowRef } from 'vue'
import * as monaco from 'monaco-editor'
import { registerPromQLLanguage, definePromQLTheme, PROMQL_LANGUAGE_ID } from '../promql/language'
import { registerCompletionProvider } from '../promql/completionProvider'
import { registerHoverProvider } from '../promql/hoverProvider'

// Initialize Monaco PromQL support (only once)
let initialized = false
function initializeMonaco() {
  if (initialized) return
  initialized = true

  registerPromQLLanguage(monaco)
  definePromQLTheme(monaco)
  registerCompletionProvider(monaco)
  registerHoverProvider(monaco)
}

const props = withDefaults(defineProps<{
  modelValue: string
  disabled?: boolean
  height?: number
  placeholder?: string
}>(), {
  height: 100,
  placeholder: 'Enter PromQL query...'
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'submit': []
}>()

const containerRef = ref<HTMLElement | null>(null)
const editorInstance = shallowRef<monaco.editor.IStandaloneCodeEditor | null>(null)

// Track if component is mounted
const isMounted = ref(false)

// Internal value for two-way binding
const internalValue = computed({
  get: () => props.modelValue,
  set: (value: string) => emit('update:modelValue', value)
})

// Create editor on mount
onMounted(() => {
  isMounted.value = true

  if (!containerRef.value) return

  // Initialize Monaco once
  initializeMonaco()

  // Create editor
  const editor = monaco.editor.create(containerRef.value, {
    value: props.modelValue,
    language: PROMQL_LANGUAGE_ID,
    theme: 'promql-dark',
    minimap: { enabled: false },
    lineNumbers: 'on',
    wordWrap: 'on',
    scrollBeyondLastLine: false,
    automaticLayout: true,
    fontSize: 13,
    fontFamily: "'Monaco', 'Menlo', 'Ubuntu Mono', monospace",
    padding: { top: 8, bottom: 8 },
    renderLineHighlight: 'line',
    lineHeight: 20,
    folding: false,
    glyphMargin: false,
    lineDecorationsWidth: 8,
    lineNumbersMinChars: 3,
    overviewRulerBorder: false,
    hideCursorInOverviewRuler: true,
    scrollbar: {
      vertical: 'auto',
      horizontal: 'auto',
      verticalScrollbarSize: 8,
      horizontalScrollbarSize: 8
    },
    suggest: {
      showIcons: true,
      showStatusBar: true,
      preview: true,
      previewMode: 'prefix'
    },
    quickSuggestions: {
      other: true,
      comments: false,
      strings: true
    },
    acceptSuggestionOnEnter: 'on',
    tabCompletion: 'on',
    readOnly: props.disabled
  })

  editorInstance.value = editor

  // Listen for content changes
  editor.onDidChangeModelContent(() => {
    const value = editor.getValue()
    if (value !== props.modelValue) {
      emit('update:modelValue', value)
    }
  })

  // Handle Ctrl+Enter to submit
  editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, () => {
    emit('submit')
  })
})

// Clean up on unmount
onUnmounted(() => {
  isMounted.value = false
  if (editorInstance.value) {
    editorInstance.value.dispose()
    editorInstance.value = null
  }
})

// Sync external value changes to editor
watch(() => props.modelValue, (newValue) => {
  if (editorInstance.value && editorInstance.value.getValue() !== newValue) {
    editorInstance.value.setValue(newValue)
  }
})

// Handle disabled state
watch(() => props.disabled, (disabled) => {
  if (editorInstance.value) {
    editorInstance.value.updateOptions({ readOnly: disabled })
  }
})

// Handle height changes
watch(() => props.height, () => {
  if (editorInstance.value) {
    editorInstance.value.layout()
  }
})

// Focus the editor
function focus() {
  editorInstance.value?.focus()
}

// Expose methods
defineExpose({ focus })
</script>

<template>
  <div class="monaco-query-editor" :class="{ disabled }">
    <div
      ref="containerRef"
      class="editor-container"
      :style="{ height: `${height}px` }"
    ></div>
    <div v-if="!modelValue && !editorInstance" class="placeholder">
      {{ placeholder }}
    </div>
  </div>
</template>

<style scoped>
.monaco-query-editor {
  position: relative;
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  overflow: hidden;
  background: #1e1e2e;
}

.monaco-query-editor.disabled {
  opacity: 0.6;
}

.editor-container {
  width: 100%;
  min-height: 60px;
}

.placeholder {
  position: absolute;
  top: 8px;
  left: 48px;
  color: var(--text-tertiary);
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 13px;
  pointer-events: none;
}

/* Fix Monaco editor styling */
:deep(.monaco-editor) {
  border-radius: 6px;
}

:deep(.monaco-editor .margin) {
  background: #1e1e2e !important;
}

:deep(.monaco-editor .monaco-scrollable-element > .scrollbar > .slider) {
  background: rgba(255, 255, 255, 0.2) !important;
}

:deep(.monaco-editor .monaco-scrollable-element > .scrollbar > .slider:hover) {
  background: rgba(255, 255, 255, 0.3) !important;
}
</style>

// frontend/src/components/MonacoQueryEditor.tsx
import * as monaco from 'monaco-editor'
import { useEffect, useId, useRef, useState } from 'react'
import '@/monaco/setupWorkers'
import { registerCompletionProvider } from '@/promql/completionProvider'
import { registerHoverProvider } from '@/promql/hoverProvider'
import {
  definePromQLLightTheme,
  definePromQLTheme,
  PROMQL_LANGUAGE_ID,
  registerPromQLLanguage,
} from '@/promql/language'
import { useThemeStore } from '@/stores/themeStore'
import '@/components/monaco-query-editor.css'

type QueryLanguage = 'promql' | 'logql' | 'logsql'

function getMonacoLanguageId(language: QueryLanguage): string {
  if (language === 'logql' || language === 'logsql') {
    return language
  }
  return PROMQL_LANGUAGE_ID
}

let initialized = false
function initializeMonaco() {
  if (initialized) return
  initialized = true

  registerPromQLLanguage(monaco)
  definePromQLTheme(monaco)
  definePromQLLightTheme(monaco)
  registerCompletionProvider(monaco)
  registerHoverProvider(monaco)
}

type MonacoQueryEditorProps = {
  value: string
  onChange: (value: string) => void
  onSubmit?: () => void
  disabled?: boolean
  height?: number
  placeholder?: string
  language?: QueryLanguage
  compact?: boolean
}

export function MonacoQueryEditor({
  value,
  onChange,
  onSubmit,
  disabled = false,
  height = 100,
  placeholder = 'Enter PromQL query...',
  language = 'promql',
  compact = false,
}: MonacoQueryEditorProps) {
  const containerRef = useRef<HTMLDivElement | null>(null)
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const onChangeRef = useRef(onChange)
  const onSubmitRef = useRef(onSubmit)
  const isDark = useThemeStore((state) => state.isDark)

  useEffect(() => {
    onChangeRef.current = onChange
  }, [onChange])

  useEffect(() => {
    onSubmitRef.current = onSubmit
  }, [onSubmit])
  const [isFocused, setIsFocused] = useState(false)
  const placeholderId = useId()
  const showPlaceholder = !value && !isFocused

  // biome-ignore lint/correctness/useExhaustiveDependencies: Monaco editor is created once; theme/language/value sync in separate effects
  useEffect(() => {
    if (!containerRef.current) return

    initializeMonaco()

    const editor = monaco.editor.create(containerRef.current, {
      value,
      language: getMonacoLanguageId(language),
      theme: isDark ? 'promql-dark' : 'promql-light',
      minimap: { enabled: false },
      lineNumbers: compact ? 'off' : 'on',
      wordWrap: 'on',
      scrollBeyondLastLine: false,
      automaticLayout: true,
      fontSize: 13,
      fontFamily: "'JetBrains Mono', 'Menlo', 'Ubuntu Mono', monospace",
      padding: { top: compact ? 0 : 8, bottom: compact ? 0 : 8 },
      renderLineHighlight: compact ? 'none' : 'line',
      lineHeight: 20,
      folding: false,
      glyphMargin: false,
      lineDecorationsWidth: compact ? 0 : 8,
      lineNumbersMinChars: compact ? 0 : 3,
      overviewRulerBorder: false,
      hideCursorInOverviewRuler: true,
      fixedOverflowWidgets: true,
      scrollbar: {
        vertical: 'auto',
        horizontal: 'auto',
        verticalScrollbarSize: 8,
        horizontalScrollbarSize: 8,
      },
      suggest: {
        showIcons: true,
        showStatusBar: true,
        preview: true,
        previewMode: 'prefix',
      },
      quickSuggestions: {
        other: true,
        comments: false,
        strings: true,
      },
      acceptSuggestionOnEnter: 'on',
      tabCompletion: 'on',
      readOnly: disabled,
    })

    editorRef.current = editor

    const contentDisposable = editor.onDidChangeModelContent(() => {
      const nextValue = editor.getValue()
      onChangeRef.current(nextValue)
    })

    const focusDisposable = editor.onDidFocusEditorText(() => {
      setIsFocused(true)
    })

    const blurDisposable = editor.onDidBlurEditorText(() => {
      setIsFocused(false)
    })

    editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, () => {
      onSubmitRef.current?.()
    })

    return () => {
      contentDisposable.dispose()
      focusDisposable.dispose()
      blurDisposable.dispose()
      editor.dispose()
      editorRef.current = null
    }
  }, [])

  useEffect(() => {
    editorRef.current?.updateOptions({ readOnly: disabled })
  }, [disabled])

  useEffect(() => {
    if (editorRef.current && editorRef.current.getValue() !== value) {
      editorRef.current.setValue(value)
    }
  }, [value])

  useEffect(() => {
    monaco.editor.setTheme(isDark ? 'promql-dark' : 'promql-light')
  }, [isDark])

  useEffect(() => {
    const model = editorRef.current?.getModel()
    if (model) {
      monaco.editor.setModelLanguage(model, getMonacoLanguageId(language))
    }
  }, [language])

  // biome-ignore lint/correctness/useExhaustiveDependencies: relayout when editor height prop changes
  useEffect(() => {
    editorRef.current?.layout()
  }, [height])

  return (
    <div
      className={`relative overflow-hidden rounded-md bg-[var(--color-surface-container-high)] transition-colors duration-[var(--motion-fast)] ease-[var(--ease-standard)] focus-within:shadow-[var(--shadow-focus)] ${compact ? 'px-3 py-3' : ''} ${disabled ? 'pointer-events-none opacity-60' : ''}`}
      data-testid="monaco-query-editor"
    >
      <div
        ref={containerRef}
        className={`w-full ${compact ? 'min-h-[20px]' : 'min-h-[60px]'}`}
        style={{ height: `${height}px` }}
      />
      {showPlaceholder ? (
        <div
          id={placeholderId}
          className={`pointer-events-none absolute font-mono text-[13px] text-[var(--color-outline)] ${compact ? 'top-3 left-3' : 'top-2 left-12'}`}
        >
          {placeholder}
        </div>
      ) : null}
    </div>
  )
}
