// frontend/src/components/PanelEditModal.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { fetchDataSourceLabels } from '@/api/datasources'
import { createPanel, updatePanel } from '@/api/panels'
import { ChartBuilderPreview } from '@/components/ChartBuilderPreview'
import { ClickHouseSQLEditor } from '@/components/ClickHouseSQLEditor'
import { CloudWatchQueryEditor } from '@/components/CloudWatchQueryEditor'
import {
  CHART_BUILDER_DEFAULT_QUERY,
  CHART_BUILDER_SUBTITLE,
  CHART_BUILDER_TYPES,
  chartBuilderPinLabel,
  chartBuilderTypeLabel,
  isChartBuilderType,
  resolveChartBuilderTitle,
} from '@/components/chartBuilder'
import { ElasticsearchQueryEditor } from '@/components/ElasticsearchQueryEditor'
import { LogQLQueryBuilder } from '@/components/LogQLQueryBuilder'
import { PanelTypeOptions } from '@/components/panelEdit/PanelTypeOptions'
import {
  buildPanelTypeGroups,
  DEFAULT_GRID_POS,
  getDefaultQuerySignal,
  getQueryMode,
  isQuerySignal,
  isSignalDatasourceType,
  type QuerySignal,
  validatePanelSave,
} from '@/components/panelEdit/panelEditHelpers'
import {
  readQueryNumber,
  readQueryString,
  readThresholds,
  type Threshold,
  thresholdsForQuery,
  toThreshold,
} from '@/components/panelEdit/thresholdFields'
import { ensurePanelTypesRegistered } from '@/components/panels/registerPanelTypes'
import { QueryBuilder } from '@/components/QueryBuilder'
import { useDatasources } from '@/hooks/useDatasources'
import { useOrganization } from '@/hooks/useOrganization'
import type { DataSource } from '@/types/datasource'
import { isLogsType, isTracingType } from '@/types/datasource'
import type { Panel } from '@/types/panel'
import { lookupPanel } from '@/utils/panelRegistry'

ensurePanelTypesRegistered()

type PanelEditModalProps = {
  dashboardId: string
  panel?: Panel
  onClose: () => void
  onSaved: (panel: Panel) => void
}

const inputClass =
  'w-full rounded-lg px-3 py-2.5 text-sm transition focus:outline-none focus:ring-2 disabled:cursor-not-allowed disabled:opacity-50'
const selectClass =
  'w-full cursor-pointer appearance-none rounded-lg px-3 py-2.5 pr-10 text-sm transition focus:outline-none focus:ring-2 disabled:cursor-not-allowed disabled:opacity-50'
const fieldStyle = {
  backgroundColor: 'var(--color-surface-container-low)',
  color: 'var(--color-on-surface)',
  border: '1px solid var(--color-outline-variant)',
} as const

function isUnsupportedPanelType(panelType: string): boolean {
  const status = lookupPanel(panelType)?.supportStatus
  if (panelType === 'heatmap') return status !== 'ready'
  return status === 'unsupported'
}

export function PanelEditModal({ dashboardId, panel, onClose, onSaved }: PanelEditModalProps) {
  const isEditing = Boolean(panel)
  const { currentOrgId } = useOrganization()
  const { data: datasources = [] } = useDatasources(currentOrgId)

  const [title, setTitle] = useState(panel?.title ?? '')
  const [panelType, setPanelType] = useState(panel?.type ?? 'line_chart')
  const [selectedDatasourceId, setSelectedDatasourceId] = useState(
    readQueryString(panel?.query, 'datasource_id'),
  )
  const [queryText, setQueryText] = useState(
    readQueryString(panel?.query, 'promql') ||
      readQueryString(panel?.query, 'expr') ||
      (panel ? '' : CHART_BUILDER_DEFAULT_QUERY),
  )
  const [querySignal, setQuerySignal] = useState<QuerySignal>(
    isQuerySignal(panel?.query?.signal)
      ? (panel?.query?.signal as QuerySignal)
      : getDefaultQuerySignal(panel?.type ?? 'line_chart'),
  )

  const [gaugeMin, setGaugeMin] = useState(readQueryNumber(panel?.query, 'min', 0))
  const [gaugeMax, setGaugeMax] = useState(readQueryNumber(panel?.query, 'max', 100))
  const [gaugeUnit, setGaugeUnit] = useState(readQueryString(panel?.query, 'unit'))
  const [gaugeDecimals, setGaugeDecimals] = useState(readQueryNumber(panel?.query, 'decimals', 2))
  const [gaugeThresholds, setGaugeThresholds] = useState<Threshold[]>(() => {
    const existing = readThresholds(panel?.query)
    return existing.length > 0 ? existing : [toThreshold(80, '#ff6b6b')]
  })

  const [pieDisplayAs, setPieDisplayAs] = useState<'pie' | 'donut'>(
    panel?.query?.displayAs === 'donut' ? 'donut' : 'pie',
  )
  const [pieShowLegend, setPieShowLegend] = useState(panel?.query?.showLegend !== false)
  const [pieShowLabels, setPieShowLabels] = useState(panel?.query?.showLabels !== false)

  const [statUnit, setStatUnit] = useState(readQueryString(panel?.query, 'unit'))
  const [statDecimals, setStatDecimals] = useState(readQueryNumber(panel?.query, 'decimals', 2))
  const [statShowTrend, setStatShowTrend] = useState(panel?.query?.showTrend !== false)
  const [statShowSparkline, setStatShowSparkline] = useState(panel?.query?.showSparkline !== false)
  const [statThresholds, setStatThresholds] = useState<Threshold[]>(() =>
    readThresholds(panel?.query),
  )

  const [traceService, setTraceService] = useState(readQueryString(panel?.query, 'service'))
  const [traceLimit, setTraceLimit] = useState(() => {
    const limit = readQueryNumber(panel?.query, 'limit', 50)
    return Math.max(1, Math.min(200, Math.floor(limit)))
  })

  const [indexedLabels, setIndexedLabels] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const panelTypeGroups = useMemo(() => buildPanelTypeGroups(), [])

  const currentQueryMode = getQueryMode(panelType)
  const needsDatasource = currentQueryMode !== 'none'
  const isTracePanelType = currentQueryMode === 'traces'
  const isLogsPanelType = currentQueryMode === 'logs'
  const isBuiltinTracePanel = panelType === 'trace_list' || panelType === 'trace_heatmap'
  const isGaugeType = panelType === 'gauge'
  const isPieType = panelType === 'pie'
  const isStatType = panelType === 'stat'
  const panelTypeUnsupported = isUnsupportedPanelType(panelType)
  const showChartBuilderTypeChips =
    isChartBuilderType(panelType) && (isEditing ? !panelTypeUnsupported : true)
  const hideFullTypeSelect = showChartBuilderTypeChips && !isEditing

  const selectedDatasource: DataSource | null = useMemo(
    () => datasources.find((ds) => ds.id === selectedDatasourceId) ?? null,
    [datasources, selectedDatasourceId],
  )

  const isClickHouseDatasource = selectedDatasource?.type === 'clickhouse'
  const isCloudWatchDatasource = selectedDatasource?.type === 'cloudwatch'
  const isElasticsearchDatasource = selectedDatasource?.type === 'elasticsearch'
  const isSignalDatasource = isSignalDatasourceType(selectedDatasource?.type)
  const isNativeLogsDatasource =
    selectedDatasource?.type === 'loki' || selectedDatasource?.type === 'victorialogs'
  const logQueryLanguage = selectedDatasource?.type === 'victorialogs' ? 'logsql' : 'logql'

  const availableDatasources = useMemo(() => {
    if (isTracePanelType) {
      return datasources.filter((ds) => isTracingType(ds.type))
    }
    if (isLogsPanelType) {
      return datasources.filter((ds) => isLogsType(ds.type))
    }
    return datasources
  }, [datasources, isLogsPanelType, isTracePanelType])

  useEffect(() => {
    if (isTracePanelType || isLogsPanelType) {
      setSelectedDatasourceId((current) => {
        if (availableDatasources.some((ds) => ds.id === current)) return current
        return availableDatasources[0]?.id ?? ''
      })
      return
    }

    setSelectedDatasourceId((current) => {
      if (current && !datasources.some((ds) => ds.id === current)) return ''
      return current
    })
  }, [availableDatasources, datasources, isLogsPanelType, isTracePanelType])

  const previousPanelTypeRef = useRef(panelType)
  useEffect(() => {
    if (previousPanelTypeRef.current === panelType) return
    previousPanelTypeRef.current = panelType
    if (!isSignalDatasource) return
    setQuerySignal(getDefaultQuerySignal(panelType))
  }, [panelType, isSignalDatasource])

  const previousDatasourceTypeRef = useRef(selectedDatasource?.type)
  useEffect(() => {
    const nextType = selectedDatasource?.type
    const prevType = previousDatasourceTypeRef.current
    previousDatasourceTypeRef.current = nextType
    if (!nextType || nextType === prevType) return
    if (!isSignalDatasourceType(nextType)) return
    setQuerySignal(getDefaultQuerySignal(panelType))
  }, [selectedDatasource?.type, panelType])

  useEffect(() => {
    if (!selectedDatasourceId || !isLogsPanelType || !isNativeLogsDatasource) {
      setIndexedLabels([])
      return
    }

    let cancelled = false
    void fetchDataSourceLabels(selectedDatasourceId)
      .then((labels) => {
        if (!cancelled) setIndexedLabels(labels)
      })
      .catch(() => {
        if (!cancelled) setIndexedLabels([])
      })

    return () => {
      cancelled = true
    }
  }, [selectedDatasourceId, isLogsPanelType, isNativeLogsDatasource])

  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [onClose])

  function handleNonTraceSignalChange(signal: 'logs' | 'metrics') {
    setQuerySignal(signal)
  }

  function addGaugeThreshold() {
    setGaugeThresholds((current) => {
      const lastValue = current.length > 0 ? current[current.length - 1].value + 10 : 50
      return [...current, toThreshold(lastValue, '#feca57')]
    })
  }

  function removeGaugeThreshold(id: string) {
    setGaugeThresholds((current) => current.filter((threshold) => threshold.id !== id))
  }

  function updateGaugeThreshold(id: string, patch: Partial<Pick<Threshold, 'value' | 'color'>>) {
    setGaugeThresholds((current) =>
      current.map((threshold) => (threshold.id === id ? { ...threshold, ...patch } : threshold)),
    )
  }

  function addStatThreshold() {
    setStatThresholds((current) => {
      const lastValue = current.length > 0 ? current[current.length - 1].value + 10 : 50
      return [...current, toThreshold(lastValue, '#feca57')]
    })
  }

  function removeStatThreshold(id: string) {
    setStatThresholds((current) => current.filter((threshold) => threshold.id !== id))
  }

  function updateStatThreshold(id: string, patch: Partial<Pick<Threshold, 'value' | 'color'>>) {
    setStatThresholds((current) =>
      current.map((threshold) => (threshold.id === id ? { ...threshold, ...patch } : threshold)),
    )
  }

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault()

    const size =
      isEditing && panel?.grid_pos
        ? { w: panel.grid_pos.w, h: panel.grid_pos.h }
        : { w: DEFAULT_GRID_POS.w, h: DEFAULT_GRID_POS.h }

    const resolvedTitle = isEditing ? title.trim() : resolveChartBuilderTitle(title, queryText)

    const validationError = validatePanelSave({
      title: resolvedTitle,
      panelType,
      size,
      queryMode: currentQueryMode,
      selectedDatasourceId,
      queryText,
      gaugeMin: isGaugeType ? gaugeMin : undefined,
      gaugeMax: isGaugeType ? gaugeMax : undefined,
    })
    if (validationError) {
      setError(validationError)
      return
    }

    if (panelTypeUnsupported && !(isEditing && panelType === panel?.type)) {
      const unsupportedLabel = chartBuilderTypeLabel(panelType)
      setError(`${unsupportedLabel} is not supported`)
      return
    }

    const query: Record<string, unknown> = {}

    if (!needsDatasource) {
      const reg = lookupPanel(panelType)
      if (reg) Object.assign(query, reg.defaultQuery)
    } else {
      if (selectedDatasourceId) {
        query.datasource_id = selectedDatasourceId
      }

      const trimmedQuery = queryText.trim()
      if (trimmedQuery && !isBuiltinTracePanel) {
        if (selectedDatasourceId) {
          query.expr = trimmedQuery
        } else {
          query.promql = trimmedQuery
        }
      }

      if (isSignalDatasource) {
        if ((isCloudWatchDatasource || isElasticsearchDatasource) && querySignal === 'traces') {
          query.signal = panelType === 'logs' ? 'logs' : 'metrics'
        } else {
          query.signal = querySignal
        }
      }

      if (isBuiltinTracePanel) {
        const trimmedService = traceService.trim()
        if (trimmedService) query.service = trimmedService
        const normalizedTraceLimit = Number.isFinite(traceLimit)
          ? Math.max(1, Math.min(200, Math.floor(traceLimit)))
          : 50
        query.limit = normalizedTraceLimit
      }
    }

    if (isGaugeType) {
      query.min = gaugeMin
      query.max = gaugeMax
      query.unit = gaugeUnit
      query.decimals = gaugeDecimals
      query.thresholds = thresholdsForQuery(gaugeThresholds)
    }

    if (isPieType) {
      query.displayAs = pieDisplayAs
      query.showLegend = pieShowLegend
      query.showLabels = pieShowLabels
    }

    if (isStatType) {
      query.unit = statUnit
      query.decimals = statDecimals
      query.showTrend = statShowTrend
      query.showSparkline = statShowSparkline
      if (statThresholds.length > 0) {
        query.thresholds = thresholdsForQuery(statThresholds)
      }
    }

    const finalQuery = Object.keys(query).length > 0 ? query : undefined

    setLoading(true)
    setError(null)

    try {
      if (isEditing && panel) {
        const updated = await updatePanel(panel.id, {
          title: resolvedTitle,
          type: panelType,
          query: finalQuery,
        })
        onSaved(updated)
      } else {
        const created = await createPanel(dashboardId, {
          title: resolvedTitle,
          type: panelType,
          grid_pos: DEFAULT_GRID_POS,
          query: finalQuery,
        })
        onSaved(created)
      }
    } catch {
      setError(isEditing ? 'Failed to update panel' : 'Failed to create panel')
    } finally {
      setLoading(false)
    }
  }

  const showQueryBlock = needsDatasource && (!isTracePanelType || isSignalDatasource)
  const previewTypeLabel = isChartBuilderType(panelType)
    ? chartBuilderTypeLabel(panelType)
    : (lookupPanel(panelType)?.label ?? chartBuilderTypeLabel(panelType))

  return createPortal(
    <div
      className="fixed inset-0 z-50"
      data-testid="panel-edit-modal"
      style={{ backgroundColor: 'var(--color-surface)' }}
    >
      <form
        role="dialog"
        aria-modal="true"
        aria-labelledby="panel-edit-title"
        className="relative flex h-full w-full flex-col gap-4 overflow-auto p-6 min-[425px]:flex-row"
        data-testid="chart-builder"
        onSubmit={(event) => void handleSubmit(event)}
      >
        <div
          className="flex min-h-0 w-full min-w-0 max-w-[360px] shrink-0 flex-col gap-3 overflow-auto min-[425px]:h-full min-[425px]:w-[360px]"
          data-testid="chart-builder-config"
        >
          <div className="flex items-start justify-between gap-2">
            <h2
              id="panel-edit-title"
              className="m-0 text-[22px] font-semibold leading-normal"
              style={{ color: 'var(--color-on-surface)' }}
            >
              {isEditing ? 'Edit panel' : 'Add panel'}
            </h2>
            <button
              type="button"
              className="cursor-pointer rounded-lg px-2 py-1 text-[13px] leading-normal"
              style={{ color: 'var(--color-on-surface-variant)' }}
              data-testid="panel-edit-close-btn"
              onClick={onClose}
            >
              Close
            </button>
          </div>
          {!isEditing ? (
            <p
              className="m-0 text-[13px] leading-normal"
              style={{ color: 'var(--color-on-surface-variant)' }}
              data-testid="chart-builder-subtitle"
            >
              {CHART_BUILDER_SUBTITLE}
            </p>
          ) : null}

          <div className={isEditing ? 'flex flex-col gap-2' : 'sr-only'}>
            <label
              htmlFor="panel-title"
              className="text-sm font-medium"
              style={{ color: 'var(--color-on-surface)' }}
            >
              Title
            </label>
            <input
              id="panel-title"
              type="text"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              placeholder="Panel title"
              disabled={loading}
              autoComplete="off"
              data-testid="panel-title-input"
              className={inputClass}
              style={fieldStyle}
            />
          </div>

          {showChartBuilderTypeChips ? (
            <div className="flex w-full flex-col gap-2" data-testid="chart-builder-types">
              {CHART_BUILDER_TYPES.map((entry) => {
                const selected = panelType === entry.type
                const chipUnsupported = isUnsupportedPanelType(entry.type)
                return (
                  <button
                    key={entry.type}
                    type="button"
                    data-testid={`chart-builder-type-${entry.type}`}
                    aria-pressed={selected}
                    disabled={loading || chipUnsupported}
                    className="w-full cursor-pointer rounded-lg p-2.5 text-left text-[13px] leading-normal disabled:cursor-not-allowed disabled:opacity-50"
                    style={{
                      backgroundColor: selected
                        ? 'var(--color-surface-container-high)'
                        : 'var(--color-surface-container-low)',
                      borderWidth: '1px',
                      borderStyle: 'solid',
                      borderColor: selected
                        ? 'var(--color-primary)'
                        : 'var(--color-surface-container-high)',
                      color: 'var(--color-on-surface)',
                      fontWeight: selected ? 500 : 400,
                    }}
                    onClick={() => {
                      if (chipUnsupported) return
                      setPanelType(entry.type)
                    }}
                  >
                    {entry.label}
                  </button>
                )
              })}
            </div>
          ) : null}

          <div className={hideFullTypeSelect ? 'sr-only' : 'flex flex-col gap-2'}>
            <label
              htmlFor="panel-type"
              className="text-sm font-medium"
              style={{ color: 'var(--color-on-surface)' }}
            >
              Panel Type
            </label>
            <select
              id="panel-type"
              value={panelType}
              onChange={(event) => setPanelType(event.target.value)}
              disabled={loading}
              data-testid="panel-type-select"
              className={selectClass}
              style={fieldStyle}
            >
              {panelTypeGroups.map((group) => (
                <optgroup key={group.id} label={group.label}>
                  {group.options.map((option) => (
                    <option key={option.value} value={option.value} disabled={option.disabled}>
                      {option.label}
                    </option>
                  ))}
                </optgroup>
              ))}
            </select>
          </div>

          {needsDatasource && datasources.length > 0 ? (
            <div>
              <label
                htmlFor="panel-datasource"
                className="mb-2 block text-sm font-medium"
                style={{ color: 'var(--color-on-surface)' }}
              >
                Data Source
              </label>
              <select
                id="panel-datasource"
                value={selectedDatasourceId}
                onChange={(event) => setSelectedDatasourceId(event.target.value)}
                disabled={loading}
                data-testid="panel-datasource-select"
                className={selectClass}
                style={fieldStyle}
              >
                {isTracePanelType ? (
                  <option value="">Select tracing datasource</option>
                ) : isLogsPanelType ? (
                  <option value="">Select logs datasource</option>
                ) : (
                  <option value="">Default (Prometheus)</option>
                )}
                {availableDatasources.map((ds) => (
                  <option key={ds.id} value={ds.id}>
                    {ds.name} ({ds.type})
                  </option>
                ))}
              </select>
            </div>
          ) : null}

          {showQueryBlock ? (
            <div
              className="flex w-full flex-col gap-2 rounded-lg p-3"
              style={{
                backgroundColor: 'var(--color-surface-container-low)',
                borderWidth: '1px',
                borderStyle: 'solid',
                borderColor: 'var(--color-surface-container-high)',
              }}
            >
              <div
                className="text-[11px] font-medium leading-normal"
                style={{ color: 'var(--color-on-surface-variant)' }}
              >
                Query
              </div>
              {isLogsPanelType && isNativeLogsDatasource ? (
                <LogQLQueryBuilder
                  value={queryText}
                  onChange={setQueryText}
                  queryLanguage={logQueryLanguage}
                  datasourceId={selectedDatasourceId}
                  indexedLabels={indexedLabels}
                  disabled={loading}
                />
              ) : isClickHouseDatasource ? (
                <ClickHouseSQLEditor
                  value={queryText}
                  onChange={setQueryText}
                  signal={querySignal}
                  showSignalSelector
                  disabled={loading}
                  onSignalChange={setQuerySignal}
                />
              ) : isCloudWatchDatasource ? (
                <CloudWatchQueryEditor
                  value={queryText}
                  onChange={setQueryText}
                  signal={querySignal === 'traces' ? 'metrics' : querySignal}
                  disabled={loading}
                  onSignalChange={handleNonTraceSignalChange}
                />
              ) : isElasticsearchDatasource ? (
                <ElasticsearchQueryEditor
                  value={queryText}
                  onChange={setQueryText}
                  signal={querySignal === 'traces' ? 'metrics' : querySignal}
                  disabled={loading}
                  onSignalChange={handleNonTraceSignalChange}
                />
              ) : isEditing ? (
                <QueryBuilder
                  value={queryText}
                  onChange={setQueryText}
                  disabled={loading}
                  datasourceId={selectedDatasourceId}
                />
              ) : (
                <input
                  id="promql-query"
                  data-testid="promql-query-input"
                  value={queryText}
                  disabled={loading}
                  onChange={(event) => setQueryText(event.target.value)}
                  className="w-full border-none bg-transparent p-0 font-mono text-[12px] leading-normal outline-none disabled:cursor-not-allowed disabled:opacity-50"
                  style={{ color: 'var(--color-on-surface)' }}
                />
              )}
            </div>
          ) : null}

          <PanelTypeOptions
            loading={loading}
            isBuiltinTracePanel={isBuiltinTracePanel}
            isGaugeType={isGaugeType}
            isPieType={isPieType}
            isStatType={isStatType}
            traceService={traceService}
            setTraceService={setTraceService}
            traceLimit={traceLimit}
            setTraceLimit={setTraceLimit}
            gaugeMin={gaugeMin}
            setGaugeMin={setGaugeMin}
            gaugeMax={gaugeMax}
            setGaugeMax={setGaugeMax}
            gaugeUnit={gaugeUnit}
            setGaugeUnit={setGaugeUnit}
            gaugeDecimals={gaugeDecimals}
            setGaugeDecimals={setGaugeDecimals}
            gaugeThresholds={gaugeThresholds}
            addGaugeThreshold={addGaugeThreshold}
            removeGaugeThreshold={removeGaugeThreshold}
            updateGaugeThreshold={updateGaugeThreshold}
            pieDisplayAs={pieDisplayAs}
            setPieDisplayAs={setPieDisplayAs}
            pieShowLegend={pieShowLegend}
            setPieShowLegend={setPieShowLegend}
            pieShowLabels={pieShowLabels}
            setPieShowLabels={setPieShowLabels}
            statUnit={statUnit}
            setStatUnit={setStatUnit}
            statDecimals={statDecimals}
            setStatDecimals={setStatDecimals}
            statShowTrend={statShowTrend}
            setStatShowTrend={setStatShowTrend}
            statShowSparkline={statShowSparkline}
            setStatShowSparkline={setStatShowSparkline}
            statThresholds={statThresholds}
            addStatThreshold={addStatThreshold}
            removeStatThreshold={removeStatThreshold}
            updateStatThreshold={updateStatThreshold}
          />

          {error ? (
            <div
              className="rounded-lg px-4 py-3 text-sm"
              style={{
                backgroundColor: 'color-mix(in srgb, var(--color-error) 10%, transparent)',
                color: 'var(--color-error)',
              }}
              data-testid="panel-edit-error"
            >
              {error}
            </div>
          ) : null}

          <div className="flex items-center gap-3">
            <button
              type="button"
              className="w-fit cursor-pointer rounded-lg p-2.5 text-[12px] font-medium leading-normal"
              style={{ color: 'var(--color-on-surface-variant)' }}
              data-testid="panel-edit-cancel-btn"
              onClick={onClose}
            >
              Cancel
            </button>
            <button
              type="submit"
              data-testid="panel-edit-save-btn"
              className="w-fit cursor-pointer rounded-lg p-2.5 text-[12px] font-semibold leading-normal disabled:cursor-not-allowed disabled:opacity-50"
              style={{
                backgroundColor: 'var(--color-primary)',
                color: 'var(--primary-foreground)',
              }}
              disabled={loading}
            >
              {loading
                ? 'Saving...'
                : isEditing
                  ? 'Save Changes'
                  : chartBuilderPinLabel(selectedDatasource)}
            </button>
          </div>
        </div>

        <ChartBuilderPreview typeLabel={previewTypeLabel} />
      </form>
    </div>,
    document.body,
  )
}

// frontend/src/components/PanelEditModal.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { X, Plus, Trash2 } from 'lucide-vue-next'
import type { Panel } from '../types/panel'
import type { DataSource } from '../types/datasource'
import { createPanel, updatePanel } from '../api/panels'
import { useDatasource } from '../composables/useDatasource'
import { useOrganization } from '../composables/useOrganization'
import QueryBuilder from './QueryBuilder.vue'

interface Threshold {
  value: number
  color: string
}

const props = defineProps<{
  panel?: Panel
  dashboardId: string
}>()

const emit = defineEmits<{
  close: []
  saved: []
}>()

const { currentOrg } = useOrganization()
const { datasources, fetchDatasources } = useDatasource()

const isEditing = computed(() => !!props.panel)

const title = ref(props.panel?.title || '')
const panelType = ref(props.panel?.type || 'line_chart')
const selectedDatasourceId = ref(
  typeof props.panel?.query?.datasource_id === 'string' ? props.panel.query.datasource_id : ''
)
// Extract promql/expr from query config, or use empty string
const promqlQuery = ref(
  typeof props.panel?.query?.promql === 'string'
    ? props.panel.query.promql
    : typeof props.panel?.query?.expr === 'string'
      ? props.panel.query.expr
      : ''
)

onMounted(() => {
  if (currentOrg.value) {
    fetchDatasources(currentOrg.value.id)
  }
})

// Gauge-specific options
const gaugeMin = ref(
  typeof props.panel?.query?.min === 'number' ? props.panel.query.min : 0
)
const gaugeMax = ref(
  typeof props.panel?.query?.max === 'number' ? props.panel.query.max : 100
)
const gaugeUnit = ref(
  typeof props.panel?.query?.unit === 'string' ? props.panel.query.unit : ''
)
const gaugeDecimals = ref(
  typeof props.panel?.query?.decimals === 'number' ? props.panel.query.decimals : 2
)
const gaugeThresholds = ref<Threshold[]>(
  Array.isArray(props.panel?.query?.thresholds)
    ? (props.panel.query.thresholds as Threshold[])
    : [{ value: 80, color: '#ff6b6b' }]
)

// Pie chart-specific options
const pieDisplayAs = ref<'pie' | 'donut'>(
  props.panel?.query?.displayAs === 'donut' ? 'donut' : 'pie'
)
const pieShowLegend = ref(
  props.panel?.query?.showLegend !== false
)
const pieShowLabels = ref(
  props.panel?.query?.showLabels !== false
)

// Stat panel-specific options
const statUnit = ref(
  typeof props.panel?.query?.unit === 'string' ? props.panel.query.unit : ''
)
const statDecimals = ref(
  typeof props.panel?.query?.decimals === 'number' ? props.panel.query.decimals : 2
)
const statShowTrend = ref(
  props.panel?.query?.showTrend !== false
)
const statShowSparkline = ref(
  props.panel?.query?.showSparkline !== false
)
const statThresholds = ref<Threshold[]>(
  Array.isArray(props.panel?.query?.thresholds)
    ? (props.panel.query.thresholds as Threshold[])
    : []
)

const loading = ref(false)
const error = ref<string | null>(null)

const isGaugeType = computed(() => panelType.value === 'gauge')
const isPieType = computed(() => panelType.value === 'pie')
const isStatType = computed(() => panelType.value === 'stat')

function addThreshold() {
  const lastValue = gaugeThresholds.value.length > 0
    ? gaugeThresholds.value[gaugeThresholds.value.length - 1].value + 10
    : 50
  gaugeThresholds.value.push({ value: lastValue, color: '#feca57' })
}

function removeThreshold(index: number) {
  gaugeThresholds.value.splice(index, 1)
}

function addStatThreshold() {
  const lastValue = statThresholds.value.length > 0
    ? statThresholds.value[statThresholds.value.length - 1].value + 10
    : 50
  statThresholds.value.push({ value: lastValue, color: '#feca57' })
}

function removeStatThreshold(index: number) {
  statThresholds.value.splice(index, 1)
}

async function handleSubmit() {
  if (!title.value.trim()) {
    error.value = 'Title is required'
    return
  }

  // Build query config
  const query: Record<string, unknown> = {}

  if (selectedDatasourceId.value) {
    query.datasource_id = selectedDatasourceId.value
    query.expr = promqlQuery.value.trim()
  } else if (promqlQuery.value.trim()) {
    query.promql = promqlQuery.value.trim()
  }

  // Add gauge-specific config if gauge type is selected
  if (isGaugeType.value) {
    query.min = gaugeMin.value
    query.max = gaugeMax.value
    query.unit = gaugeUnit.value
    query.decimals = gaugeDecimals.value
    query.thresholds = gaugeThresholds.value
  }

  // Add pie chart-specific config if pie type is selected
  if (isPieType.value) {
    query.displayAs = pieDisplayAs.value
    query.showLegend = pieShowLegend.value
    query.showLabels = pieShowLabels.value
  }

  // Add stat panel-specific config if stat type is selected
  if (isStatType.value) {
    query.unit = statUnit.value
    query.decimals = statDecimals.value
    query.showTrend = statShowTrend.value
    query.showSparkline = statShowSparkline.value
    if (statThresholds.value.length > 0) {
      query.thresholds = statThresholds.value
    }
  }

  const finalQuery = Object.keys(query).length > 0 ? query : undefined

  loading.value = true
  error.value = null

  try {
    if (isEditing.value && props.panel) {
      await updatePanel(props.panel.id, {
        title: title.value.trim(),
        type: panelType.value,
        query: finalQuery
      })
    } else {
      await createPanel(props.dashboardId, {
        title: title.value.trim(),
        type: panelType.value,
        grid_pos: { x: 0, y: 0, w: 6, h: 4 },
        query: finalQuery
      })
    }
    emit('saved')
  } catch {
    error.value = isEditing.value ? 'Failed to update panel' : 'Failed to create panel'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="modal-overlay" @click.self="emit('close')">
    <div class="modal">
      <header class="modal-header">
        <h2>{{ isEditing ? 'Edit Panel' : 'Add Panel' }}</h2>
        <button class="btn-close" @click="emit('close')">
          <X :size="20" />
        </button>
      </header>

      <form @submit.prevent="handleSubmit">
        <div class="form-row">
          <div class="form-group">
            <label for="title">Title <span class="required">*</span></label>
            <input
              id="title"
              v-model="title"
              type="text"
              placeholder="Panel title"
              :disabled="loading"
              autocomplete="off"
            />
          </div>

          <div class="form-group form-group-small">
            <label for="type">Panel Type</label>
            <select id="type" v-model="panelType" :disabled="loading">
              <option value="line_chart">Line Chart</option>
              <option value="bar_chart">Bar Chart</option>
              <option value="pie">Pie Chart</option>
              <option value="gauge">Gauge</option>
              <option value="stat">Stat</option>
              <option value="table">Table</option>
              <option value="logs">Logs</option>
            </select>
          </div>
        </div>

        <div v-if="datasources.length > 0" class="form-group">
          <label for="datasource">Data Source</label>
          <select id="datasource" v-model="selectedDatasourceId" :disabled="loading">
            <option value="">Default (Prometheus)</option>
            <option v-for="ds in datasources" :key="ds.id" :value="ds.id">
              {{ ds.name }} ({{ ds.type }})
            </option>
          </select>
        </div>

        <div class="form-group query-builder-group">
          <label>Query</label>
          <QueryBuilder
            v-model="promqlQuery"
            :disabled="loading"
          />
        </div>

        <!-- Gauge Configuration -->
        <div v-if="isGaugeType" class="gauge-config">
          <div class="config-header">
            <h4>Gauge Options</h4>
          </div>

          <div class="form-row form-row-4">
            <div class="form-group">
              <label for="gauge-min">Min</label>
              <input
                id="gauge-min"
                v-model.number="gaugeMin"
                type="number"
                :disabled="loading"
              />
            </div>
            <div class="form-group">
              <label for="gauge-max">Max</label>
              <input
                id="gauge-max"
                v-model.number="gaugeMax"
                type="number"
                :disabled="loading"
              />
            </div>
            <div class="form-group">
              <label for="gauge-unit">Unit</label>
              <input
                id="gauge-unit"
                v-model="gaugeUnit"
                type="text"
                placeholder="%"
                :disabled="loading"
              />
            </div>
            <div class="form-group">
              <label for="gauge-decimals">Decimals</label>
              <input
                id="gauge-decimals"
                v-model.number="gaugeDecimals"
                type="number"
                min="0"
                max="10"
                :disabled="loading"
              />
            </div>
          </div>

          <div class="thresholds-section">
            <div class="thresholds-header">
              <label>Thresholds</label>
              <button type="button" class="btn btn-sm" @click="addThreshold" :disabled="loading">
                <Plus :size="14" />
                Add
              </button>
            </div>
            <div class="thresholds-list">
              <div v-for="(threshold, index) in gaugeThresholds" :key="index" class="threshold-row">
                <input
                  v-model.number="threshold.value"
                  type="number"
                  placeholder="Value"
                  :disabled="loading"
                  class="threshold-value"
                />
                <input
                  v-model="threshold.color"
                  type="color"
                  :disabled="loading"
                  class="threshold-color"
                />
                <button
                  type="button"
                  class="btn-icon btn-icon-danger"
                  @click="removeThreshold(index)"
                  :disabled="loading"
                  title="Remove threshold"
                >
                  <Trash2 :size="14" />
                </button>
              </div>
              <p v-if="gaugeThresholds.length === 0" class="thresholds-empty">
                No thresholds configured. Values below any threshold will show green.
              </p>
            </div>
          </div>
        </div>

        <!-- Pie Chart Configuration -->
        <div v-if="isPieType" class="pie-config">
          <div class="config-header">
            <h4>Pie Chart Options</h4>
          </div>

          <div class="form-row form-row-3">
            <div class="form-group">
              <label for="pie-display">Display Style</label>
              <select id="pie-display" v-model="pieDisplayAs" :disabled="loading">
                <option value="pie">Pie</option>
                <option value="donut">Donut</option>
              </select>
            </div>
            <div class="form-group">
              <label for="pie-legend">Show Legend</label>
              <div class="checkbox-wrapper">
                <input
                  id="pie-legend"
                  v-model="pieShowLegend"
                  type="checkbox"
                  :disabled="loading"
                />
                <label for="pie-legend">Display legend</label>
              </div>
            </div>
            <div class="form-group">
              <label for="pie-labels">Show Labels</label>
              <div class="checkbox-wrapper">
                <input
                  id="pie-labels"
                  v-model="pieShowLabels"
                  type="checkbox"
                  :disabled="loading"
                />
                <label for="pie-labels">Display value labels</label>
              </div>
            </div>
          </div>
        </div>

        <!-- Stat Panel Configuration -->
        <div v-if="isStatType" class="stat-config">
          <div class="config-header">
            <h4>Stat Panel Options</h4>
          </div>

          <div class="form-row form-row-2">
            <div class="form-group">
              <label for="stat-unit">Unit</label>
              <input
                id="stat-unit"
                v-model="statUnit"
                type="text"
                placeholder="%"
                :disabled="loading"
              />
            </div>
            <div class="form-group">
              <label for="stat-decimals">Decimals</label>
              <input
                id="stat-decimals"
                v-model.number="statDecimals"
                type="number"
                min="0"
                max="10"
                :disabled="loading"
              />
            </div>
          </div>

          <div class="form-row form-row-2">
            <div class="form-group">
              <label>
                <input
                  type="checkbox"
                  v-model="statShowTrend"
                  :disabled="loading"
                />
                Show Trend Indicator
              </label>
            </div>
            <div class="form-group">
              <label>
                <input
                  type="checkbox"
                  v-model="statShowSparkline"
                  :disabled="loading"
                />
                Show Sparkline
              </label>
            </div>
          </div>

          <div class="thresholds-section">
            <div class="thresholds-header">
              <label>Thresholds (Optional)</label>
              <button type="button" class="btn btn-sm" @click="addStatThreshold" :disabled="loading">
                <Plus :size="14" />
                Add
              </button>
            </div>
            <div class="thresholds-list">
              <div v-for="(threshold, index) in statThresholds" :key="index" class="threshold-row">
                <input
                  v-model.number="threshold.value"
                  type="number"
                  placeholder="Value"
                  :disabled="loading"
                  class="threshold-value"
                />
                <input
                  v-model="threshold.color"
                  type="color"
                  :disabled="loading"
                  class="threshold-color"
                />
                <button
                  type="button"
                  class="btn-icon btn-icon-danger"
                  @click="removeStatThreshold(index)"
                  :disabled="loading"
                  title="Remove threshold"
                >
                  <Trash2 :size="14" />
                </button>
              </div>
              <p v-if="statThresholds.length === 0" class="thresholds-empty">
                No thresholds configured.
              </p>
            </div>
          </div>
        </div>

        <div v-if="error" class="error-message">{{ error }}</div>

        <div class="modal-actions">
          <button type="button" class="btn btn-secondary" @click="emit('close')" :disabled="loading">
            Cancel
          </button>
          <button type="submit" class="btn btn-primary" :disabled="loading">
            {{ loading ? 'Saving...' : (isEditing ? 'Save Changes' : 'Add Panel') }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.7);
  backdrop-filter: blur(4px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
  animation: fadeIn 0.2s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

.modal {
  background: var(--bg-secondary);
  border: 1px solid var(--border-primary);
  border-radius: 12px;
  width: 100%;
  max-width: 640px;
  max-height: 90vh;
  overflow-y: auto;
  animation: slideUp 0.3s ease-out;
}

@keyframes slideUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.25rem 1.5rem;
  border-bottom: 1px solid var(--border-primary);
  position: sticky;
  top: 0;
  background: var(--bg-secondary);
  z-index: 1;
}

.modal-header h2 {
  margin: 0;
  font-size: 1.125rem;
  font-weight: 600;
  color: var(--text-primary);
}

.btn-close {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  background: transparent;
  border: none;
  border-radius: 6px;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.btn-close:hover {
  background: var(--bg-hover);
  color: var(--text-primary);
}

form {
  padding: 1.5rem;
}

.form-row {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 1rem;
}

.form-group {
  margin-bottom: 1.25rem;
}

.form-group-small {
  min-width: 160px;
}

.query-builder-group {
  border-top: 1px solid var(--border-primary);
  padding-top: 1.25rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--text-primary);
}

.required {
  color: var(--accent-danger);
}

.form-group input,
.form-group textarea,
.form-group select {
  width: 100%;
  padding: 0.75rem 1rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  font-size: 0.875rem;
  color: var(--text-primary);
  transition: border-color 0.2s, box-shadow 0.2s;
}

.form-group input::placeholder,
.form-group textarea::placeholder {
  color: var(--text-tertiary);
}

.form-group input:focus,
.form-group textarea:focus,
.form-group select:focus {
  outline: none;
  border-color: var(--accent-primary);
  box-shadow: var(--focus-ring);
}

.form-group input:disabled,
.form-group textarea:disabled,
.form-group select:disabled {
  background: var(--bg-primary);
  color: var(--text-tertiary);
  cursor: not-allowed;
}

.form-group select {
  cursor: pointer;
  appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23a0a0a0' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 0.75rem center;
  padding-right: 2.5rem;
}

.error-message {
  padding: 0.75rem 1rem;
  background: rgba(255, 107, 107, 0.1);
  border: 1px solid rgba(255, 107, 107, 0.3);
  border-radius: 6px;
  color: var(--accent-danger);
  font-size: 0.875rem;
  margin-bottom: 1.25rem;
}

.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.75rem;
  margin-top: 0.5rem;
}

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.625rem 1.25rem;
  border: 1px solid transparent;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-secondary {
  background: var(--bg-tertiary);
  border-color: var(--border-primary);
  color: var(--text-primary);
}

.btn-secondary:hover:not(:disabled) {
  background: var(--bg-hover);
  border-color: var(--border-secondary);
}

.btn-primary {
  background: var(--accent-primary);
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background: var(--accent-primary-hover);
}

/* Gauge configuration styles */
.gauge-config {
  border-top: 1px solid var(--border-primary);
  padding-top: 1.25rem;
  margin-bottom: 1.25rem;
}

.config-header h4 {
  margin: 0 0 1rem 0;
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--text-primary);
}

.form-row-4 {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 0.75rem;
}

.form-row-4 .form-group {
  margin-bottom: 0.75rem;
}

.thresholds-section {
  margin-top: 1rem;
}

.thresholds-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
}

.thresholds-header label {
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--text-primary);
}

.btn-sm {
  padding: 0.375rem 0.625rem;
  font-size: 0.75rem;
  gap: 0.25rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  color: var(--text-primary);
}

.btn-sm:hover:not(:disabled) {
  background: var(--bg-hover);
}

.thresholds-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.threshold-row {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.threshold-value {
  flex: 1;
  padding: 0.5rem 0.75rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  font-size: 0.875rem;
  color: var(--text-primary);
}

.threshold-value:focus {
  outline: none;
  border-color: var(--accent-primary);
}

.threshold-color {
  width: 40px;
  height: 36px;
  padding: 2px;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  cursor: pointer;
}

.threshold-color::-webkit-color-swatch-wrapper {
  padding: 2px;
}

.threshold-color::-webkit-color-swatch {
  border: none;
  border-radius: 4px;
}

.btn-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  padding: 0;
  background: transparent;
  border: none;
  border-radius: 6px;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.btn-icon:hover {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.btn-icon-danger:hover {
  background: rgba(255, 107, 107, 0.15);
  color: var(--accent-danger);
}

.thresholds-empty {
  font-size: 0.75rem;
  color: var(--text-tertiary);
  margin: 0;
  padding: 0.5rem;
  text-align: center;
}
</style>
