// frontend/src/components/Panel.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Pencil, Trash2, AlertCircle, BarChart3 } from 'lucide-vue-next'
import type { Panel } from '../types/panel'
import { useTimeRange } from '../composables/useTimeRange'
import { useProm } from '../composables/useProm'
import LineChart, { type ChartSeries } from './LineChart.vue'
import BarChart from './BarChart.vue'
import GaugeChart, { type Threshold } from './GaugeChart.vue'
import PieChart, { type PieDataItem } from './PieChart.vue'
import StatPanel, { type DataPoint } from './StatPanel.vue'
import TablePanel from './TablePanel.vue'

const props = defineProps<{
  panel: Panel
}>()

defineEmits<{
  edit: [panel: Panel]
  delete: [panel: Panel]
}>()

const { timeRange, onRefresh } = useTimeRange()

// Setup Prometheus query
const promqlQuery = computed(() => props.panel.query?.promql || '')

// Create refs for useProm
const queryRef = ref(promqlQuery.value)
const startRef = computed(() => Math.floor(timeRange.value.start / 1000))
const endRef = computed(() => Math.floor(timeRange.value.end / 1000))

// Watch for query changes
watch(promqlQuery, (newQuery) => {
  queryRef.value = newQuery
}, { immediate: true })

const { chartData: promChartData, loading, error, fetch: refetch } = useProm({
  query: queryRef,
  start: startRef,
  end: endRef,
  autoFetch: true,
})

// Use chart data from useProm
const chartData = promChartData

// Transform to chart series format
const chartSeries = computed(() => {
  return chartData.value.series.map((s) => ({
    name: s.name,
    data: s.data,
  }))
})

// Get the latest value for gauge chart (from first series)
const gaugeValue = computed(() => {
  if (chartData.value.series.length === 0) return 0
  const firstSeries = chartData.value.series[0]
  if (firstSeries.data.length === 0) return 0
  return firstSeries.data[firstSeries.data.length - 1].value
})

// Extract gauge config from panel query
const gaugeConfig = computed(() => {
  const query = props.panel.query || {}
  return {
    min: typeof query.min === 'number' ? query.min : 0,
    max: typeof query.max === 'number' ? query.max : 100,
    unit: typeof query.unit === 'string' ? query.unit : '',
    decimals: typeof query.decimals === 'number' ? query.decimals : 2,
    thresholds: Array.isArray(query.thresholds)
      ? (query.thresholds as Threshold[])
      : [],
  }
})

// Transform chartData to PieChart data format (use latest value from each series)
const pieData = computed<PieDataItem[]>(() => {
  return chartData.value.series.map((s) => ({
    name: s.name,
    value: s.data.length > 0 ? s.data[s.data.length - 1].value : 0,
  }))
})

// Extract pie chart config from panel query
const pieConfig = computed(() => {
  const query = props.panel.query || {}
  return {
    displayAs: (query.displayAs === 'donut' ? 'donut' : 'pie') as 'pie' | 'donut',
    showLegend: query.showLegend !== false,
    showLabels: query.showLabels !== false,
  }
})

// Auto-refresh on time range change
watch([timeRange, onRefresh], () => {
  if (hasQuery.value) {
    refetch()
  }
})

// Transform data to StatPanel format
const statData = computed<DataPoint[]>(() => {
  if (chartData.value.series.length === 0) return []
  const firstSeries = chartData.value.series[0]
  return firstSeries.data.map((d) => ({
    timestamp: d.timestamp,
    value: d.value,
  }))
})

// Get the current (latest) value for stat panel
const statValue = computed(() => {
  if (chartData.value.series.length === 0) return 0
  const firstSeries = chartData.value.series[0]
  if (firstSeries.data.length === 0) return 0
  return firstSeries.data[firstSeries.data.length - 1].value
})

// Get the previous value for trend calculation (second to last data point)
const statPreviousValue = computed(() => {
  if (chartData.value.series.length === 0) return undefined
  const firstSeries = chartData.value.series[0]
  if (firstSeries.data.length < 2) return undefined
  return firstSeries.data[firstSeries.data.length - 2].value
})

// Extract stat panel config
const statConfig = computed(() => {
  const query = props.panel.query || {}
  return {
    unit: typeof query.unit === 'string' ? query.unit : '',
    decimals: typeof query.decimals === 'number' ? query.decimals : 2,
    showTrend: query.showTrend !== false,
    showSparkline: query.showSparkline !== false,
    thresholds: Array.isArray(query.thresholds) ? (query.thresholds as Threshold[]) : [],
  }
})

const hasQuery = computed(() => !!promqlQuery.value)
const isLineChart = computed(() => props.panel.type === 'line_chart')
const isBarChart = computed(() => props.panel.type === 'bar_chart')
const isGaugeChart = computed(() => props.panel.type === 'gauge')
const isPieChart = computed(() => props.panel.type === 'pie')
const isStatPanel = computed(() => props.panel.type === 'stat')
const isTablePanel = computed(() => props.panel.type === 'table')
</script>

<template>
  <div class="panel">
    <div class="panel-header">
      <h3 class="panel-title">{{ panel.title }}</h3>
      <div class="panel-actions">
        <button class="panel-action-btn" @click="$emit('edit', panel)" title="Edit panel">
          <Pencil :size="16" />
        </button>
        <button class="panel-action-btn" @click="$emit('delete', panel)" title="Delete panel">
          <Trash2 :size="16" />
        </button>
      </div>
    </div>
    <div class="panel-body">
      <div v-if="!hasQuery" class="panel-state panel-no-query">
        <BarChart3 :size="48" class="icon-muted" />
        <p class="text-muted">No query configured</p>
        <button class="btn-primary" @click="$emit('edit', panel)">Configure Panel</button>
      </div>
      <div v-else-if="loading" class="panel-state">
        <div class="spinner"></div>
        <p class="text-muted">Loading data...</p>
      </div>
      <div v-else-if="error" class="panel-state panel-error">
        <AlertCircle :size="48" class="icon-error" />
        <p class="error-text">{{ error }}</p>
      </div>
      <div v-else-if="isLineChart && chartSeries.length > 0" class="chart-container">
        <LineChart :series="chartSeries" />
      </div>
      <div v-else-if="isBarChart && chartSeries.length > 0" class="chart-container">
        <BarChart :series="chartSeries" />
      </div>
      <div v-else-if="isGaugeChart && chartSeries.length > 0" class="chart-container">
        <GaugeChart
          :value="gaugeValue"
          :min="gaugeConfig.min"
          :max="gaugeConfig.max"
          :unit="gaugeConfig.unit"
          :decimals="gaugeConfig.decimals"
          :thresholds="gaugeConfig.thresholds"
        />
      </div>
      <div v-else-if="isPieChart && pieData.length > 0" class="chart-container">
        <PieChart
          :data="pieData"
          :display-as="pieConfig.displayAs"
          :show-legend="pieConfig.showLegend"
          :show-labels="pieConfig.showLabels"
        />
      </div>
      <div v-else-if="isStatPanel && statData.length > 0" class="chart-container">
        <StatPanel
          :value="statValue"
          :previous-value="statPreviousValue"
          :data="statData"
          :label="panel.title"
          :unit="statConfig.unit"
          :decimals="statConfig.decimals"
          :thresholds="statConfig.thresholds"
          :show-trend="statConfig.showTrend"
          :show-sparkline="statConfig.showSparkline"
        />
      </div>
      <div v-else-if="isTablePanel && chartSeries.length > 0" class="chart-container">
        <TablePanel :series="chartSeries" />
      </div>
      <div v-else-if="chartSeries.length === 0" class="panel-state panel-no-data">
        <AlertCircle :size="48" class="icon-warning" />
        <p class="text-muted">No data available</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.panel {
  background: var(--bg-secondary);
  border: 1px solid var(--border-primary);
  border-radius: 8px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  height: 100%;
  transition: border-color 0.2s, box-shadow 0.2s;
}

.panel:hover {
  border-color: var(--border-secondary);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border-primary);
  background: var(--bg-tertiary);
}

.panel-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0;
}

.panel-actions {
  display: flex;
  gap: 4px;
}

.panel-action-btn {
  padding: 4px;
  background: transparent;
  border: none;
  color: var(--text-tertiary);
  cursor: pointer;
  border-radius: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
}

.panel-action-btn:hover {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.panel-body {
  flex: 1;
  padding: 16px;
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.chart-container {
  flex: 1;
  min-height: 0;
}

.panel-state {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
}

.panel-no-query,
.panel-no-data {
  color: var(--text-tertiary);
}

.panel-error {
  color: var(--accent-danger);
}

.icon-muted {
  color: var(--text-tertiary);
}

.icon-warning {
  color: var(--accent-warning);
}

.icon-error {
  color: var(--accent-danger);
}

.text-muted {
  color: var(--text-secondary);
  font-size: 14px;
  margin: 0;
}

.error-text {
  color: var(--accent-danger);
  font-size: 14px;
  margin: 0;
}

.spinner {
  width: 32px;
  height: 32px;
  border: 3px solid var(--border-primary);
  border-top-color: var(--accent-primary);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.btn-primary {
  padding: 8px 16px;
  background: var(--accent-primary);
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

.btn-primary:hover {
  background: var(--accent-primary-hover);
}
</style>

// frontend/src/components/Panel.tsx
import { AlertCircle, BarChart3, Pencil, Trash2 } from 'lucide-react'
import { useMemo } from 'react'
import { BarChart } from '@/components/BarChart'
import { GaugeChart, type Threshold } from '@/components/GaugeChart'
import { LineChart } from '@/components/LineChart'
import { LogViewer } from '@/components/LogViewer'
import { PieChart, type PieDataItem } from '@/components/PieChart'
import { ensurePanelTypesRegistered } from '@/components/panels/registerPanelTypes'
import { StatPanel } from '@/components/StatPanel'
import { TablePanel } from '@/components/TablePanel'
import { TraceHeatmapPanel } from '@/components/TraceHeatmapPanel'
import { TraceListPanel } from '@/components/TraceListPanel'
import { useCrosshairSync } from '@/contexts/CrosshairSyncContext'
import { useDashboardVariables } from '@/contexts/VariablesContext'
import { usePanelData } from '@/hooks/usePanelData'
import { useTimeRange } from '@/hooks/useTimeRange'
import type { Panel as PanelType } from '@/types/panel'

ensurePanelTypesRegistered()

const WIDE_PANEL_COLS = 8

function panelQueryExpr(query: PanelType['query']): string {
  if (!query) return ''
  if (typeof query.expr === 'string' && query.expr.trim()) return query.expr
  if (typeof query.promql === 'string' && query.promql.trim()) return query.promql
  return ''
}

type PanelProps = {
  panel: PanelType
  onEdit?: (panel: PanelType) => void
  onDelete?: (panel: PanelType) => void
  onOpenTrace?: (payload: { datasourceId: string; traceId: string }) => void
}

export function Panel({ panel, onEdit, onDelete, onOpenTrace }: PanelProps) {
  const { interpolate, variables } = useDashboardVariables()
  const { groupId } = useCrosshairSync()
  const { selectedPreset, isCustomRange } = useTimeRange()
  const variableSignature = useMemo(
    () =>
      variables
        .map((variable) => {
          const current = Array.isArray(variable.current)
            ? variable.current.join(',')
            : (variable.current ?? '')
          return `${variable.name}:${current}`
        })
        .join('|'),
    [variables],
  )
  const { loading, error, chartSeries, logs, traceSummaries, hasQuery, registry } = usePanelData(
    panel,
    interpolate,
    variableSignature,
  )

  const gaugeValue = useMemo(() => {
    if (chartSeries.length === 0) return 0
    const firstSeries = chartSeries[0]
    if (!firstSeries || firstSeries.data.length === 0) return 0
    return firstSeries.data[firstSeries.data.length - 1]!.value
  }, [chartSeries])

  const gaugeConfig = useMemo(() => {
    const query = panel.query || {}
    return {
      min: typeof query.min === 'number' ? query.min : 0,
      max: typeof query.max === 'number' ? query.max : 100,
      unit: typeof query.unit === 'string' ? query.unit : '',
      decimals: typeof query.decimals === 'number' ? query.decimals : 2,
      thresholds: Array.isArray(query.thresholds) ? (query.thresholds as Threshold[]) : [],
    }
  }, [panel.query])

  const pieData = useMemo<PieDataItem[]>(
    () =>
      chartSeries.map((series) => ({
        name: series.name,
        value: series.data.length > 0 ? series.data[series.data.length - 1]!.value : 0,
      })),
    [chartSeries],
  )

  const pieConfig = useMemo(() => {
    const query = panel.query || {}
    return {
      displayAs: (query.displayAs === 'donut' ? 'donut' : 'pie') as 'pie' | 'donut',
      showLegend: query.showLegend !== false,
      showLabels: query.showLabels !== false,
    }
  }, [panel.query])

  const statData = useMemo(
    () =>
      chartSeries[0]?.data.map((point) => ({
        timestamp: point.timestamp,
        value: point.value,
      })) ?? [],
    [chartSeries],
  )

  const statValue = useMemo(() => {
    if (statData.length === 0) return 0
    return statData[statData.length - 1]!.value
  }, [statData])

  const statPreviousValue = useMemo(() => {
    if (statData.length < 2) return undefined
    return statData[statData.length - 2]!.value
  }, [statData])

  const statConfig = useMemo(() => {
    const query = panel.query || {}
    return {
      unit: typeof query.unit === 'string' ? query.unit : '',
      decimals: typeof query.decimals === 'number' ? query.decimals : 2,
      showTrend: query.showTrend !== false,
      showSparkline: query.showSparkline !== false,
      thresholds: Array.isArray(query.thresholds) ? (query.thresholds as Threshold[]) : [],
    }
  }, [panel.query])

  const textContent = typeof panel.query?.content === 'string' ? panel.query.content : ''

  const isLineChart = panel.type === 'line_chart'
  const isBarChart = panel.type === 'bar_chart'
  const isGaugeChart = panel.type === 'gauge'
  const isPieChart = panel.type === 'pie'
  const isStatPanel = panel.type === 'stat'
  const isTablePanel = panel.type === 'table'
  const isLogPanel = panel.type === 'logs'
  const isTraceListPanel = panel.type === 'trace_list'
  const isTraceHeatmapPanel = panel.type === 'trace_heatmap'
  const isTextPanel = panel.type === 'text'
  const isRegistryPanel = registry !== null
  const registryEmptyState = registry?.emptyState ?? null
  const isUnsupportedRegistryPanel = registry?.supportStatus === 'unsupported'
  const isSetupRequiredRegistryPanel = registry?.supportStatus === 'setup_required'
  const isWidePanel = panel.grid_pos.w >= WIDE_PANEL_COLS
  const queryExpr = panelQueryExpr(panel.query)
  const headerMeta = isWidePanel && queryExpr ? queryExpr : isCustomRange ? '' : selectedPreset

  function handleOpenTrace(traceId: string) {
    const datasourceId = panel.query?.datasource_id
    if (typeof datasourceId !== 'string' || !datasourceId) return
    onOpenTrace?.({ datasourceId, traceId })
  }

  function renderRegistryEmptyState() {
    return (
      <div
        data-testid="panel-unsupported-empty"
        className="flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center"
        style={{ color: 'var(--color-on-surface-variant)' }}
      >
        <AlertCircle size={40} style={{ color: 'var(--color-tertiary)' }} />
        <h4 className="m-0 text-sm font-semibold" style={{ color: 'var(--color-on-surface)' }}>
          {registryEmptyState?.title ||
            (isRegistryPanel
              ? `${registry?.label || panel.type} not available in React yet`
              : 'Panel not supported yet')}
        </h4>
        <p className="m-0 max-w-sm text-xs leading-5">
          {registryEmptyState?.description ||
            'This panel type is registered but has no live React renderer yet. Use a Core panel type for live dashboard content.'}
        </p>
        {registryEmptyState?.actionLabel ? (
          <span
            className="text-[11px] font-semibold uppercase tracking-wide"
            style={{ color: 'var(--color-primary)' }}
          >
            {registryEmptyState.actionLabel}
          </span>
        ) : null}
      </div>
    )
  }

  function renderBody() {
    // Text is the only registry type with a live React body; handle it before support gates.
    if (isTextPanel) {
      return (
        <div
          className="min-h-0 flex-1 overflow-auto whitespace-pre-wrap p-3 text-sm leading-6"
          style={{ color: 'var(--color-on-surface)' }}
          data-testid="text-panel"
        >
          {textContent || 'Edit this panel to add content.'}
        </div>
      )
    }

    // Non-live registry types: skip loading/query chrome so the empty state is immediate.
    if (isUnsupportedRegistryPanel || isSetupRequiredRegistryPanel || isRegistryPanel) {
      return renderRegistryEmptyState()
    }

    if (!hasQuery) {
      return (
        <div
          className="flex flex-1 flex-col items-center justify-center gap-3"
          style={{ color: 'var(--color-outline)' }}
        >
          <BarChart3 size={48} />
          <p className="m-0 text-sm">No query configured</p>
          {onEdit ? (
            <button
              type="button"
              className="cursor-pointer rounded-lg border-0 px-4 py-2 text-sm font-medium text-white transition hover:opacity-90"
              style={{
                background:
                  'linear-gradient(135deg, var(--color-primary), var(--color-primary-dim))',
              }}
              data-testid="panel-configure-btn"
              onClick={() => onEdit(panel)}
            >
              Configure Panel
            </button>
          ) : null}
        </div>
      )
    }

    if (loading) {
      return (
        <div className="flex flex-1 flex-col items-center justify-center gap-3">
          <div
            className="h-8 w-8 animate-spin rounded-full border-[3px]"
            style={{
              borderColor: 'var(--color-outline-variant)',
              borderTopColor: 'var(--color-primary)',
            }}
          />
          <p className="m-0 text-sm" style={{ color: 'var(--color-on-surface-variant)' }}>
            Loading data...
          </p>
        </div>
      )
    }

    if (error) {
      return (
        <div className="flex flex-1 flex-col items-center justify-center gap-3">
          <AlertCircle size={48} style={{ color: 'var(--color-error)' }} />
          <p className="m-0 p-2 text-xs" style={{ color: 'var(--color-error)' }}>
            {error}
          </p>
        </div>
      )
    }

    if (isLineChart && chartSeries.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <LineChart series={chartSeries} group={groupId ?? undefined} />
        </div>
      )
    }

    if (isBarChart && chartSeries.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <BarChart series={chartSeries} />
        </div>
      )
    }

    if (isGaugeChart && chartSeries.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <GaugeChart value={gaugeValue} {...gaugeConfig} />
        </div>
      )
    }

    if (isPieChart && pieData.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <PieChart data={pieData} {...pieConfig} />
        </div>
      )
    }

    if (isStatPanel && statData.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <StatPanel
            value={statValue}
            previousValue={statPreviousValue}
            data={statData}
            label={panel.title}
            unit={statConfig.unit}
            decimals={statConfig.decimals}
            thresholds={statConfig.thresholds}
            showTrend={statConfig.showTrend}
            showSparkline={statConfig.showSparkline}
          />
        </div>
      )
    }

    if (isTablePanel && chartSeries.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <TablePanel series={chartSeries} />
        </div>
      )
    }

    if (isLogPanel && logs.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <LogViewer logs={logs} />
        </div>
      )
    }

    if (isTraceListPanel && traceSummaries.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <TraceListPanel traces={traceSummaries} onOpenTrace={handleOpenTrace} />
        </div>
      )
    }

    if (isTraceHeatmapPanel && traceSummaries.length > 0) {
      return (
        <div className="min-h-0 flex-1">
          <TraceHeatmapPanel traces={traceSummaries} onOpenTrace={handleOpenTrace} />
        </div>
      )
    }

    return (
      <div
        className="flex flex-1 flex-col items-center justify-center gap-3"
        style={{ color: 'var(--color-on-surface-variant)' }}
      >
        <AlertCircle size={48} style={{ color: 'var(--color-tertiary)' }} />
        <p className="m-0 text-sm">No data available</p>
      </div>
    )
  }

  return (
    <div
      className="relative flex h-full flex-col gap-2 overflow-hidden rounded-lg p-[var(--panel-padding)]"
      style={{
        backgroundColor: 'var(--color-surface-container-low)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--color-stroke-subtle)',
      }}
      data-testid={`dashboard-panel-${panel.id}`}
    >
      <div className="panel-header flex items-center justify-between gap-2">
        <h3
          className={`min-w-0 truncate font-medium ${isWidePanel ? 'text-[13px]' : 'text-xs'}`}
          style={{
            color: isWidePanel ? 'var(--color-on-surface)' : 'var(--color-on-surface-variant)',
          }}
          data-testid="panel-title"
        >
          {panel.title}
        </h3>
        <div className="flex min-w-0 shrink-0 items-center gap-1">
          {headerMeta ? (
            <span
              className={`max-w-[220px] truncate ${isWidePanel ? 'font-mono text-[11px]' : 'text-[11px]'}`}
              style={{ color: 'var(--color-on-surface-variant)' }}
              data-testid="panel-header-meta"
              title={headerMeta}
            >
              {headerMeta}
            </span>
          ) : null}
          {(onEdit || onDelete) && (
            <div className="panel-actions flex gap-1">
              {onEdit ? (
                <button
                  type="button"
                  className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-md border-0 bg-transparent transition hover:opacity-80"
                  style={{ color: 'var(--color-outline)' }}
                  data-testid="panel-edit-btn"
                  title="Edit panel"
                  onClick={() => onEdit(panel)}
                >
                  <Pencil size={16} />
                </button>
              ) : null}
              {onDelete ? (
                <button
                  type="button"
                  className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-md border-0 bg-transparent transition hover:opacity-80"
                  style={{ color: 'var(--color-outline)' }}
                  data-testid="panel-delete-btn"
                  title="Delete panel"
                  onClick={() => onDelete(panel)}
                >
                  <Trash2 size={16} />
                </button>
              ) : null}
            </div>
          )}
        </div>
      </div>

      <div className="flex min-h-0 flex-1 flex-col overflow-hidden">{renderBody()}</div>
    </div>
  )
}
