// frontend/src/components/QueryBuilder.tsx
import { ChevronDown, ChevronUp, Code, Layers, Plus, Search, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { MonacoQueryEditor } from '@/components/MonacoQueryEditor'
import {
  AGGREGATION_FUNCTIONS,
  LABEL_OPERATORS,
  type LabelFilter,
  useQueryBuilder,
} from '@/hooks/useQueryBuilder'

const MAX_LABEL_VALUES = 500

type QueryBuilderProps = {
  value: string
  onChange: (value: string) => void
  disabled?: boolean
  datasourceId?: string
}

export function QueryBuilder({
  value,
  onChange,
  disabled = false,
  datasourceId = '',
}: QueryBuilderProps) {
  const {
    mode,
    setMode,
    metric,
    setMetric,
    labelFilters,
    aggregation,
    setAggregation,
    groupByLabels,
    rangeInterval,
    setRangeInterval,
    kValue,
    setKValue,
    codeQuery,
    setCodeQuery,
    generatedQuery,
    activeQuery,
    metricsCache,
    labelsCache,
    labelValuesCache,
    loadingMetrics,
    loadingLabelValues,
    setDatasourceId,
    loadMetrics,
    loadLabels,
    loadLabelValues,
    addLabelFilter,
    removeLabelFilter,
    updateLabelFilter,
    toggleGroupByLabel,
    setQuery,
  } = useQueryBuilder(value, datasourceId)

  const isEmittingRef = useRef(false)
  const [metricSearch, setMetricSearch] = useState('')
  const [showMetricDropdown, setShowMetricDropdown] = useState(false)
  const [showGroupBy, setShowGroupBy] = useState(false)

  const filteredMetrics = useMemo(() => {
    if (!metricSearch) return metricsCache.slice(0, 100)
    const search = metricSearch.toLowerCase()
    return metricsCache.filter((m) => m.toLowerCase().includes(search)).slice(0, 100)
  }, [metricSearch, metricsCache])

  const availableLabelsForGroupBy = useMemo(
    () => labelsCache.filter((label) => label !== '__name__'),
    [labelsCache],
  )

  const aggregationRequiresRange = useMemo(() => {
    const func = AGGREGATION_FUNCTIONS.find((f) => f.value === aggregation)
    return Boolean(func && 'requiresRange' in func && func.requiresRange)
  }, [aggregation])

  const aggregationRequiresK = useMemo(() => {
    const func = AGGREGATION_FUNCTIONS.find((f) => f.value === aggregation)
    return Boolean(func && 'requiresK' in func && func.requiresK)
  }, [aggregation])

  const builderAvailable = useMemo(() => {
    if (!codeQuery) return true
    if (mode === 'builder' && generatedQuery) return true
    if (codeQuery === generatedQuery) return true
    if (!metric) return false
    return true
  }, [codeQuery, generatedQuery, metric, mode])

  useEffect(() => {
    if (datasourceId) {
      setDatasourceId(datasourceId)
      void Promise.all([loadMetrics(), loadLabels()])
    }
  }, [datasourceId, loadLabels, loadMetrics, setDatasourceId])

  useEffect(() => {
    if (isEmittingRef.current) return
    if (value !== activeQuery) {
      setQuery(value)
    }
  }, [value, activeQuery, setQuery])

  useEffect(() => {
    isEmittingRef.current = true
    onChange(activeQuery)
    const timer = window.setTimeout(() => {
      isEmittingRef.current = false
    }, 0)
    return () => clearTimeout(timer)
  }, [activeQuery, onChange])

  function selectMetric(nextMetric: string) {
    setMetric(nextMetric)
    setMetricSearch('')
    setShowMetricDropdown(false)
  }

  function hideMetricDropdownDelayed() {
    window.setTimeout(() => setShowMetricDropdown(false), 200)
  }

  async function handleLabelChange(filter: LabelFilter, newLabel: string) {
    updateLabelFilter(filter.id, { label: newLabel, value: '' })
    if (newLabel) {
      await loadLabelValues(newLabel)
    }
  }

  function getLabelValues(labelName: string): string[] {
    const values = labelValuesCache.get(labelName) || []
    return values.slice(0, MAX_LABEL_VALUES)
  }

  return (
    <div
      className={`flex flex-col gap-4 ${disabled ? 'pointer-events-none opacity-60' : ''}`}
      data-testid="query-builder"
    >
      <div className="flex w-fit rounded-sm bg-[var(--color-surface-container-high)] p-1">
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-sm border-none bg-transparent px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:text-[var(--color-on-surface)] disabled:cursor-not-allowed disabled:opacity-40 ${mode === 'builder' ? 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm' : ''}`}
          data-testid="query-builder-mode-btn"
          onClick={() => setMode('builder')}
          disabled={disabled || !builderAvailable}
          title={!builderAvailable ? 'Query cannot be edited in builder mode' : ''}
        >
          <Layers size={14} />
          <span>Builder</span>
        </button>
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-sm border-none bg-transparent px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:text-[var(--color-on-surface)] disabled:cursor-not-allowed disabled:opacity-40 ${mode === 'code' ? 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm' : ''}`}
          data-testid="query-code-mode-btn"
          onClick={() => setMode('code')}
          disabled={disabled}
        >
          <Code size={14} />
          <span>Code</span>
        </button>
      </div>

      {mode === 'builder' ? (
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <label
              htmlFor="query-metric-search-input"
              className="text-sm font-medium text-[var(--color-on-surface)]"
            >
              Metric
            </label>
            <div className="relative">
              <div className="relative flex items-center">
                <Search
                  size={14}
                  className="pointer-events-none absolute left-3 text-[var(--color-outline)]"
                />
                <input
                  id="query-metric-search-input"
                  value={metricSearch}
                  onChange={(event) => setMetricSearch(event.target.value)}
                  type="text"
                  data-testid="query-metric-search-input"
                  className="w-full rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 pl-9 text-sm text-[var(--color-on-surface)] transition-colors duration-200 focus:ring-2 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                  placeholder="Search metrics..."
                  disabled={disabled || loadingMetrics}
                  onFocus={() => setShowMetricDropdown(true)}
                  onBlur={hideMetricDropdownDelayed}
                />
                {metric ? (
                  <span className="absolute right-3 rounded bg-[var(--color-primary)] px-2 py-0.5 font-mono text-xs text-white">
                    {metric}
                  </span>
                ) : null}
              </div>

              {showMetricDropdown && filteredMetrics.length > 0 ? (
                <div className="absolute top-[calc(100%+4px)] right-0 left-0 z-[100] max-h-[250px] overflow-y-auto rounded-sm bg-[var(--color-surface-container-low)] shadow-lg">
                  {filteredMetrics.map((m) => (
                    <button
                      key={m}
                      type="button"
                      className={`w-full cursor-pointer border-none bg-transparent px-3 py-2 text-left font-mono text-sm text-[var(--color-on-surface)] transition-colors duration-150 hover:bg-[var(--color-surface-container-high)] ${m === metric ? 'bg-[var(--color-primary)]/10 text-[var(--color-primary)]' : ''}`}
                      onMouseDown={(event) => {
                        event.preventDefault()
                        selectMetric(m)
                      }}
                    >
                      {m}
                    </button>
                  ))}
                  {loadingMetrics ? (
                    <div className="py-3 text-center text-sm text-[var(--color-outline)]">
                      Loading...
                    </div>
                  ) : null}
                </div>
              ) : null}
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium text-[var(--color-on-surface)]">
                Label Filters
              </span>
              <button
                type="button"
                className="flex items-center gap-1.5 rounded-sm px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:bg-[var(--color-surface-container-high)] hover:enabled:text-[var(--color-on-surface)]"
                data-testid="query-add-filter-btn"
                onClick={addLabelFilter}
                disabled={disabled}
              >
                <Plus size={14} />
                <span>Add Filter</span>
              </button>
            </div>

            {labelFilters.length === 0 ? (
              <div className="rounded-sm bg-[var(--color-surface-container-high)] p-4 text-center text-sm text-[var(--color-outline)]">
                No label filters. Click &quot;Add Filter&quot; to filter by labels.
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                {labelFilters.map((filter) => (
                  <div key={filter.id} className="flex items-center gap-2">
                    <select
                      value={filter.label}
                      onChange={(event) => handleLabelChange(filter, event.target.value)}
                      className="min-w-0 flex-1 cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                      disabled={disabled}
                    >
                      <option value="">Select label</option>
                      {labelsCache.map((label) => (
                        <option key={label} value={label}>
                          {label}
                        </option>
                      ))}
                    </select>

                    <select
                      value={filter.operator}
                      onChange={(event) =>
                        updateLabelFilter(filter.id, {
                          operator: event.target.value as LabelFilter['operator'],
                        })
                      }
                      className="w-[70px] flex-none cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 font-mono text-sm text-[var(--color-on-surface-variant)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                      disabled={disabled}
                    >
                      {LABEL_OPERATORS.map((op) => (
                        <option key={op.value} value={op.value}>
                          {op.label}
                        </option>
                      ))}
                    </select>

                    {getLabelValues(filter.label).length > 0 ? (
                      <select
                        value={filter.value}
                        onChange={(event) =>
                          updateLabelFilter(filter.id, { value: event.target.value })
                        }
                        className="min-w-0 flex-[1.5] cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                        disabled={disabled || loadingLabelValues === filter.label}
                      >
                        <option value="">Select value</option>
                        {getLabelValues(filter.label).map((v) => (
                          <option key={v} value={v}>
                            {v}
                          </option>
                        ))}
                      </select>
                    ) : (
                      <input
                        type="text"
                        value={filter.value}
                        onChange={(event) =>
                          updateLabelFilter(filter.id, { value: event.target.value })
                        }
                        className="min-w-0 flex-[1.5] rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                        placeholder="Value"
                        disabled={disabled}
                      />
                    )}

                    <button
                      type="button"
                      className="flex h-7 w-7 cursor-pointer items-center justify-center rounded border-none bg-transparent text-[var(--color-outline)] transition-all duration-200 hover:enabled:bg-[var(--color-error)]/10 hover:enabled:text-[var(--color-error)]"
                      onClick={() => removeLabelFilter(filter.id)}
                      disabled={disabled}
                    >
                      <X size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="flex flex-col gap-2">
            <label
              htmlFor="query-aggregation-select"
              className="text-sm font-medium text-[var(--color-on-surface)]"
            >
              Aggregation
            </label>
            <div className="flex items-center gap-4">
              <select
                id="query-aggregation-select"
                value={aggregation}
                onChange={(event) => setAggregation(event.target.value as typeof aggregation)}
                data-testid="query-aggregation-select"
                className="max-w-[200px] flex-1 cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                disabled={disabled}
              >
                {AGGREGATION_FUNCTIONS.map((agg) => (
                  <option key={agg.value} value={agg.value}>
                    {agg.label}
                  </option>
                ))}
              </select>

              {aggregationRequiresRange ? (
                <div className="flex items-center gap-2">
                  <label
                    htmlFor="query-range-input"
                    className="text-sm text-[var(--color-outline)]"
                  >
                    Range:
                  </label>
                  <input
                    id="query-range-input"
                    value={rangeInterval}
                    onChange={(event) => setRangeInterval(event.target.value)}
                    type="text"
                    data-testid="query-range-input"
                    className="w-20 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 font-mono text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                    placeholder="5m"
                    disabled={disabled}
                  />
                </div>
              ) : null}

              {aggregationRequiresK ? (
                <div className="flex items-center gap-2">
                  <label htmlFor="query-k-input" className="text-sm text-[var(--color-outline)]">
                    K:
                  </label>
                  <input
                    id="query-k-input"
                    value={kValue}
                    onChange={(event) => setKValue(Number(event.target.value))}
                    type="number"
                    min={1}
                    data-testid="query-k-input"
                    className="w-[60px] rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                    disabled={disabled}
                  />
                </div>
              ) : null}
            </div>
          </div>

          {aggregation ? (
            <div className="flex flex-col gap-2">
              <button
                type="button"
                className="flex w-full cursor-pointer items-center gap-2 border-none bg-transparent py-2 text-[var(--color-on-surface)] hover:text-[var(--color-primary)]"
                onClick={() => setShowGroupBy((prev) => !prev)}
                disabled={disabled}
              >
                <span className="text-sm font-medium">Group By</span>
                {groupByLabels.length > 0 ? (
                  <span className="inline-flex h-5 min-w-[20px] items-center justify-center rounded-sm bg-[var(--color-primary)] px-1.5 text-xs font-medium text-white">
                    {groupByLabels.length}
                  </span>
                ) : null}
                {showGroupBy ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>

              {showGroupBy ? (
                <div className="rounded-sm bg-[var(--color-surface-container-high)] p-3">
                  <div className="flex flex-wrap gap-2">
                    {availableLabelsForGroupBy.map((label) => (
                      <label
                        key={label}
                        className="flex cursor-pointer items-center gap-1.5 rounded bg-[var(--color-surface-container-low)] px-2.5 py-1.5 text-xs text-[var(--color-on-surface)] transition-all duration-200 hover:border-[var(--color-primary)]/20"
                      >
                        <input
                          type="checkbox"
                          checked={groupByLabels.includes(label)}
                          onChange={() => toggleGroupByLabel(label)}
                          disabled={disabled}
                        />
                        <span>{label}</span>
                      </label>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}

          <div className="mt-2 flex flex-col gap-2 pt-4">
            <span className="text-sm font-medium text-[var(--color-on-surface)]">
              Generated Query
            </span>
            <div className="min-h-[48px] rounded-sm bg-[var(--color-surface-container-high)] px-4 py-3">
              {generatedQuery ? (
                <code className="font-mono text-sm break-all text-[var(--color-primary)]">
                  {generatedQuery}
                </code>
              ) : (
                <span className="text-sm text-[var(--color-outline)]">
                  Select a metric to generate query
                </span>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <span className="text-sm font-medium text-[var(--color-on-surface)]">Query</span>
          <MonacoQueryEditor
            value={codeQuery}
            onChange={setCodeQuery}
            disabled={disabled}
            height={120}
            placeholder="Enter query (PromQL / MetricsQL)..."
          />
        </div>
      )}
    </div>
  )
}

// frontend/src/components/QueryBuilder.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { Search, Plus, X, Code, Layers, ChevronDown, ChevronUp } from 'lucide-vue-next'
import MonacoQueryEditor from './MonacoQueryEditor.vue'
import {
  useQueryBuilder,
  AGGREGATION_FUNCTIONS,
  LABEL_OPERATORS,
  type LabelFilter
} from '../composables/useQueryBuilder'

const props = defineProps<{
  modelValue: string
  disabled?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const {
  mode,
  metric,
  labelFilters,
  aggregation,
  groupByLabels,
  rangeInterval,
  kValue,
  codeQuery,
  generatedQuery,
  activeQuery,
  metricsCache,
  labelsCache,
  labelValuesCache,
  loadingMetrics,
  loadingLabelValues,
  loadMetrics,
  loadLabels,
  loadLabelValues,
  addLabelFilter,
  removeLabelFilter,
  updateLabelFilter,
  toggleGroupByLabel,
  setQuery
} = useQueryBuilder(props.modelValue)

// Metric search
const metricSearch = ref('')
const showMetricDropdown = ref(false)

const filteredMetrics = computed(() => {
  if (!metricSearch.value) return metricsCache.value.slice(0, 100)
  const search = metricSearch.value.toLowerCase()
  return metricsCache.value
    .filter(m => m.toLowerCase().includes(search))
    .slice(0, 100)
})

// Group by expanded state
const showGroupBy = ref(false)

// Available labels for group by (exclude __name__)
const availableLabelsForGroupBy = computed(() => {
  return labelsCache.value.filter(l => l !== '__name__')
})

// Check if aggregation requires range
const aggregationRequiresRange = computed(() => {
  const func = AGGREGATION_FUNCTIONS.find(f => f.value === aggregation.value)
  return func && 'requiresRange' in func && func.requiresRange
})

// Check if aggregation requires K value
const aggregationRequiresK = computed(() => {
  const func = AGGREGATION_FUNCTIONS.find(f => f.value === aggregation.value)
  return func && 'requiresK' in func && func.requiresK
})

// Load metadata on mount
onMounted(async () => {
  await Promise.all([loadMetrics(), loadLabels()])
})

// Sync with v-model
watch(() => props.modelValue, (newValue) => {
  if (newValue !== activeQuery.value) {
    setQuery(newValue)
  }
})

watch(activeQuery, (newValue) => {
  emit('update:modelValue', newValue)
})

// Select metric
function selectMetric(m: string) {
  metric.value = m
  metricSearch.value = ''
  showMetricDropdown.value = false
}

// Delay hiding metric dropdown (to allow click events to fire)
function hideMetricDropdownDelayed() {
  setTimeout(() => {
    showMetricDropdown.value = false
  }, 200)
}

// Handle label filter label change - preload values
async function handleLabelChange(filter: LabelFilter, newLabel: string) {
  updateLabelFilter(filter.id, { label: newLabel, value: '' })
  if (newLabel) {
    await loadLabelValues(newLabel)
  }
}

// Get cached label values
function getLabelValues(labelName: string): string[] {
  return labelValuesCache.value.get(labelName) || []
}
</script>

<template>
  <div class="query-builder" :class="{ disabled }">
    <!-- Mode Toggle -->
    <div class="mode-toggle">
      <button
        type="button"
        class="mode-btn"
        :class="{ active: mode === 'builder' }"
        @click="mode = 'builder'"
        :disabled="disabled"
      >
        <Layers :size="14" />
        <span>Builder</span>
      </button>
      <button
        type="button"
        class="mode-btn"
        :class="{ active: mode === 'code' }"
        @click="mode = 'code'"
        :disabled="disabled"
      >
        <Code :size="14" />
        <span>Code</span>
      </button>
    </div>

    <!-- Builder Mode -->
    <div v-if="mode === 'builder'" class="builder-mode">
      <!-- Metric Selector -->
      <div class="builder-section">
        <label class="section-label">Metric</label>
        <div class="metric-selector">
          <div class="search-input-wrapper">
            <Search :size="14" class="search-icon" />
            <input
              v-model="metricSearch"
              type="text"
              class="search-input"
              placeholder="Search metrics..."
              :disabled="disabled || loadingMetrics"
              @focus="showMetricDropdown = true"
              @blur="hideMetricDropdownDelayed"
            />
            <span v-if="metric" class="selected-metric">{{ metric }}</span>
          </div>

          <div v-if="showMetricDropdown && filteredMetrics.length > 0" class="dropdown">
            <div
              v-for="m in filteredMetrics"
              :key="m"
              class="dropdown-item"
              :class="{ selected: m === metric }"
              @mousedown.prevent="selectMetric(m)"
            >
              {{ m }}
            </div>
            <div v-if="loadingMetrics" class="dropdown-loading">Loading...</div>
          </div>
        </div>
      </div>

      <!-- Label Filters -->
      <div class="builder-section">
        <div class="section-header">
          <label class="section-label">Label Filters</label>
          <button
            type="button"
            class="btn-add"
            @click="addLabelFilter"
            :disabled="disabled"
          >
            <Plus :size="14" />
            <span>Add Filter</span>
          </button>
        </div>

        <div v-if="labelFilters.length === 0" class="empty-filters">
          No label filters. Click "Add Filter" to filter by labels.
        </div>

        <div v-else class="filters-list">
          <div
            v-for="filter in labelFilters"
            :key="filter.id"
            class="filter-row"
          >
            <!-- Label select -->
            <select
              :value="filter.label"
              @change="handleLabelChange(filter, ($event.target as HTMLSelectElement).value)"
              class="filter-select"
              :disabled="disabled"
            >
              <option value="">Select label</option>
              <option v-for="label in labelsCache" :key="label" :value="label">
                {{ label }}
              </option>
            </select>

            <!-- Operator select -->
            <select
              :value="filter.operator"
              @change="updateLabelFilter(filter.id, { operator: ($event.target as HTMLSelectElement).value as any })"
              class="filter-select filter-operator"
              :disabled="disabled"
            >
              <option v-for="op in LABEL_OPERATORS" :key="op.value" :value="op.value">
                {{ op.label }}
              </option>
            </select>

            <!-- Value select/input -->
            <select
              v-if="getLabelValues(filter.label).length > 0"
              :value="filter.value"
              @change="updateLabelFilter(filter.id, { value: ($event.target as HTMLSelectElement).value })"
              class="filter-select filter-value"
              :disabled="disabled || loadingLabelValues === filter.label"
            >
              <option value="">Select value</option>
              <option v-for="v in getLabelValues(filter.label)" :key="v" :value="v">
                {{ v }}
              </option>
            </select>
            <input
              v-else
              type="text"
              :value="filter.value"
              @input="updateLabelFilter(filter.id, { value: ($event.target as HTMLInputElement).value })"
              class="filter-input"
              placeholder="Value"
              :disabled="disabled"
            />

            <!-- Remove button -->
            <button
              type="button"
              class="btn-remove"
              @click="removeLabelFilter(filter.id)"
              :disabled="disabled"
            >
              <X :size="14" />
            </button>
          </div>
        </div>
      </div>

      <!-- Aggregation -->
      <div class="builder-section">
        <label class="section-label">Aggregation</label>
        <div class="aggregation-row">
          <select
            v-model="aggregation"
            class="aggregation-select"
            :disabled="disabled"
          >
            <option v-for="agg in AGGREGATION_FUNCTIONS" :key="agg.value" :value="agg.value">
              {{ agg.label }}
            </option>
          </select>

          <!-- Range input for rate/increase functions -->
          <div v-if="aggregationRequiresRange" class="range-input-group">
            <label>Range:</label>
            <input
              v-model="rangeInterval"
              type="text"
              class="range-input"
              placeholder="5m"
              :disabled="disabled"
            />
          </div>

          <!-- K value for topk/bottomk -->
          <div v-if="aggregationRequiresK" class="k-input-group">
            <label>K:</label>
            <input
              v-model.number="kValue"
              type="number"
              min="1"
              class="k-input"
              :disabled="disabled"
            />
          </div>
        </div>
      </div>

      <!-- Group By -->
      <div v-if="aggregation" class="builder-section">
        <button
          type="button"
          class="section-toggle"
          @click="showGroupBy = !showGroupBy"
          :disabled="disabled"
        >
          <span class="section-label">Group By</span>
          <span v-if="groupByLabels.length > 0" class="group-count">{{ groupByLabels.length }}</span>
          <component :is="showGroupBy ? ChevronUp : ChevronDown" :size="14" />
        </button>

        <div v-if="showGroupBy" class="group-by-section">
          <div class="group-by-list">
            <label
              v-for="label in availableLabelsForGroupBy"
              :key="label"
              class="group-by-item"
            >
              <input
                type="checkbox"
                :checked="groupByLabels.includes(label)"
                @change="toggleGroupByLabel(label)"
                :disabled="disabled"
              />
              <span>{{ label }}</span>
            </label>
          </div>
        </div>
      </div>

      <!-- Preview -->
      <div class="builder-section preview-section">
        <label class="section-label">Generated PromQL</label>
        <div class="preview-box">
          <code v-if="generatedQuery">{{ generatedQuery }}</code>
          <span v-else class="preview-placeholder">Select a metric to generate query</span>
        </div>
      </div>
    </div>

    <!-- Code Mode -->
    <div v-else class="code-mode">
      <label class="section-label">PromQL Query</label>
      <MonacoQueryEditor
        v-model="codeQuery"
        :disabled="disabled"
        :height="120"
        placeholder="Enter PromQL query..."
      />
    </div>
  </div>
</template>

<style scoped>
.query-builder {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.query-builder.disabled {
  opacity: 0.6;
  pointer-events: none;
}

.mode-toggle {
  display: flex;
  background: var(--bg-tertiary);
  border-radius: 6px;
  padding: 2px;
  width: fit-content;
}

.mode-btn {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.5rem 1rem;
  background: transparent;
  border: none;
  border-radius: 4px;
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.mode-btn:hover:not(:disabled) {
  color: var(--text-primary);
}

.mode-btn.active {
  background: var(--bg-secondary);
  color: var(--text-primary);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
}

.builder-mode,
.code-mode {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.builder-section {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.section-label {
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--text-primary);
}

.section-toggle {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0;
  background: transparent;
  border: none;
  cursor: pointer;
  color: var(--text-primary);
  width: 100%;
}

.section-toggle:hover {
  color: var(--accent-primary);
}

.group-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 20px;
  height: 20px;
  padding: 0 6px;
  background: var(--accent-primary);
  border-radius: 10px;
  font-size: 0.75rem;
  font-weight: 500;
  color: white;
}

.metric-selector {
  position: relative;
}

.search-input-wrapper {
  position: relative;
  display: flex;
  align-items: center;
}

.search-icon {
  position: absolute;
  left: 0.75rem;
  color: var(--text-tertiary);
  pointer-events: none;
}

.search-input {
  width: 100%;
  padding: 0.625rem 1rem 0.625rem 2.25rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  font-size: 0.875rem;
  color: var(--text-primary);
  transition: border-color 0.2s, box-shadow 0.2s;
}

.search-input:focus {
  outline: none;
  border-color: var(--accent-primary);
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.15);
}

.selected-metric {
  position: absolute;
  right: 0.75rem;
  padding: 0.25rem 0.5rem;
  background: var(--accent-primary);
  border-radius: 4px;
  font-size: 0.75rem;
  font-family: monospace;
  color: white;
}

.dropdown {
  position: absolute;
  top: calc(100% + 4px);
  left: 0;
  right: 0;
  max-height: 250px;
  overflow-y: auto;
  background: var(--bg-secondary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
  z-index: 100;
}

.dropdown-item {
  padding: 0.5rem 0.75rem;
  font-size: 0.8125rem;
  font-family: monospace;
  color: var(--text-primary);
  cursor: pointer;
  transition: background-color 0.15s;
}

.dropdown-item:hover {
  background: var(--bg-hover);
}

.dropdown-item.selected {
  background: var(--accent-primary);
  color: white;
}

.dropdown-loading {
  padding: 0.75rem;
  text-align: center;
  color: var(--text-tertiary);
  font-size: 0.8125rem;
}

.btn-add {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.375rem 0.75rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 500;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.btn-add:hover:not(:disabled) {
  background: var(--bg-hover);
  color: var(--text-primary);
  border-color: var(--border-secondary);
}

.empty-filters {
  padding: 1rem;
  text-align: center;
  color: var(--text-tertiary);
  font-size: 0.8125rem;
  background: var(--bg-tertiary);
  border-radius: 6px;
}

.filters-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.filter-row {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}

.filter-select,
.filter-input {
  padding: 0.5rem 0.75rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 4px;
  font-size: 0.8125rem;
  color: var(--text-primary);
  transition: border-color 0.2s;
}

.filter-select:focus,
.filter-input:focus {
  outline: none;
  border-color: var(--accent-primary);
}

.filter-select {
  flex: 1;
  min-width: 0;
  cursor: pointer;
}

.filter-operator {
  flex: 0 0 70px;
}

.filter-value {
  flex: 1.5;
}

.filter-input {
  flex: 1.5;
}

.btn-remove {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  background: transparent;
  border: none;
  border-radius: 4px;
  color: var(--text-tertiary);
  cursor: pointer;
  transition: all 0.2s;
}

.btn-remove:hover:not(:disabled) {
  background: rgba(255, 107, 107, 0.1);
  color: var(--accent-danger);
}

.aggregation-row {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.aggregation-select {
  flex: 1;
  max-width: 200px;
  padding: 0.5rem 0.75rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 4px;
  font-size: 0.8125rem;
  color: var(--text-primary);
  cursor: pointer;
}

.aggregation-select:focus {
  outline: none;
  border-color: var(--accent-primary);
}

.range-input-group,
.k-input-group {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.range-input-group label,
.k-input-group label {
  font-size: 0.8125rem;
  color: var(--text-secondary);
}

.range-input {
  width: 80px;
  padding: 0.5rem 0.75rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 4px;
  font-size: 0.8125rem;
  font-family: monospace;
  color: var(--text-primary);
}

.range-input:focus {
  outline: none;
  border-color: var(--accent-primary);
}

.k-input {
  width: 60px;
  padding: 0.5rem 0.75rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 4px;
  font-size: 0.8125rem;
  color: var(--text-primary);
}

.k-input:focus {
  outline: none;
  border-color: var(--accent-primary);
}

.group-by-section {
  padding: 0.75rem;
  background: var(--bg-tertiary);
  border-radius: 6px;
}

.group-by-list {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.group-by-item {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.375rem 0.625rem;
  background: var(--bg-secondary);
  border: 1px solid var(--border-primary);
  border-radius: 4px;
  font-size: 0.75rem;
  color: var(--text-primary);
  cursor: pointer;
  transition: all 0.2s;
}

.group-by-item:hover {
  border-color: var(--accent-primary);
}

.group-by-item input {
  accent-color: var(--accent-primary);
}

.preview-section {
  margin-top: 0.5rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border-primary);
}

.preview-box {
  padding: 0.75rem 1rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  min-height: 48px;
}

.preview-box code {
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 0.8125rem;
  color: var(--accent-primary);
  word-break: break-all;
}

.preview-placeholder {
  color: var(--text-tertiary);
  font-size: 0.8125rem;
}

.code-textarea {
  width: 100%;
  padding: 0.75rem 1rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-primary);
  border-radius: 6px;
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 0.8125rem;
  color: var(--text-primary);
  resize: vertical;
  min-height: 100px;
  transition: border-color 0.2s, box-shadow 0.2s;
}

.code-textarea::placeholder {
  color: var(--text-tertiary);
}

.code-textarea:focus {
  outline: none;
  border-color: var(--accent-primary);
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.15);
}

.code-textarea:disabled {
  background: var(--bg-primary);
  color: var(--text-tertiary);
  cursor: not-allowed;
}
</style>
